import image1 from './img/Recomendados/1.jpg';
import image2 from './img/Recomendados/2.jpg';
import image3 from './img/Recomendados/3.jpg';
import image4 from './img/Recomendados/4.jpg';
import image5 from './img/Recomendados/5.jpg';
import image6 from './img/Recomendados/6.jpg';
import image7 from './img/Recomendados/7.jpg';
import image8 from './img/Recomendados/8.jpg';
import image9 from './img/Recomendados/9.jpg';
import image10 from './img/Recomendados/10.jpg';
import image11 from './img/Recomendados/11.jpg';
import image12 from './img/Recomendados/12.jpg';
import image13 from './img/LosMasComprados/2.jpg';
import image14 from './img/LosMasComprados/3.jpg';
import image15 from './img/LosMasComprados/4.jpg';
import image16 from './img/LosMasComprados/5.jpg';
import image17 from './img/LosMasComprados/1.jpg';
import image18 from './img/LosMasComprados/6.jpg';
import image19 from './img/LosMasComprados/7.jpg';
import image20 from './img/LosMasComprados/8.jpg';
import image21 from './img/LosMasComprados/9.jpg';
import image22 from './img/LosMasComprados/10.jpg';
import image23 from './img/LosMasComprados/11.jpg';
import image24 from './img/LosMasComprados/12.jpg';
import image25 from './img/Veggie/1.jpg';
import image26 from './img/Veggie/2.jpg';
import image27 from './img/Veggie/3.jpg';
import image28 from './img/Veggie/4.jpg';
import image29 from './img/Veggie/5.jpg';
import image30 from './img/Veggie/6.jpg';
import image31 from './img/Veggie/7.jpg';
import image32 from './img/Veggie/8.jpg';
import image33 from './img/Veggie/9.jpg';
import image34 from './img/Veggie/10.jpg';
import image35 from './img/Veggie/11.jpg';
import image36 from './img/Veggie/12.jpg';
import image37 from './img/Tentaciones/1.jpg';
import image38 from './img/Tentaciones/2.jpg';
import image39 from './img/Tentaciones/3.jpg';
import image40 from './img/Tentaciones/4.jpg';
import image41 from './img/Tentaciones/5.jpg';
import image42 from './img/Tentaciones/6.jpg';
import image43 from './img/Tentaciones/7.jpg';
import image44 from './img/Tentaciones/8.jpg';
import image45 from './img/Tentaciones/9.jpg';
import image46 from './img/Tentaciones/10.jpg';
import image47 from './img/Tentaciones/11.jpg';
import image48 from './img/Tentaciones/12.jpg';
import image49 from './img/Recomendados/13.jpg';
import image50 from './img/Recomendados/14.jpg';
import image51 from './img/LosMasComprados/13.jpg';
import video1 from './img/Videos/nardalepes.jpg';
import video2 from './img/Videos/empanadas.jpg';

  const appData = {
    // Por ahora hay un solo usuario super hardcodeado
    // con sus datos, favoritos, platos comprados y packs comprados.
    usuario: {
              username: 'Pepenacho',
              nombre: 'José',
              apellido: 'Sbruzzi',
              direccion: 'Paseo Colón 850',
              tarjetaNumero: 'XXXX-XXXX-XXXX-8745',
    },
    favoritos: [9,16,18,19,49,29,34],
    comprados: [
                /*{
                  idCompra: 1,
                  idPlato: 4,
                  cantidad: 3,
                },
                {
                  idCompra: 2,
                  idPlato: 6,
                  cantidad: 8,
                },
                { 
                  idCompra: 3,
                  idPlato: 39,
                  cantidad: 2
                 }*/
                ],
                 
    packsComprados: [2],
    carrito: [
              /*{
                idPlato: 5,
                cantidad: 2,
              },
              {
                idPlato: 2,
                cantidad: 1,
              }*/
            ],
    packs: [
            {
              id: 1,
              platos: [2,3],
            },
            {
              id: 2,
              platos: [1,4],
            },
            {
              id: 3,
              platos: [5,6,3],
            }
           ],
    platos: [
              {
                id: 1,
                img: image1,
                title: 'Canelones al horno',
                author: 'Carlos Alberto “El Gato” Dumas',
                descripcion: 'Nada mejor que disfrutar de una excelente pasta con espinaca, nueces y salvia crujiente. Con su delicioso relleno de tres quesos, este canelón de vegetales dorados es un verdadero placer. Para 8 porciones, dificultad: "súper fácil".',
                ingredientes: '1 puñado de queso parmesano, rallado.250 g bañeras mascarpone.100 g de queso Taleggio rallado.2 limones, cáscara y jugo de. 1 puñado de nueces picadas.180 g de espinaca baby, picada.sal marina.pimienta negra recién molida.20 g de salvia fresca.2 perillas de mantequilla.12 hojas frescas de lasaña',
                receta: 'Pruebe estos simples canelones: son geniales como alternativa vegetariana.Precalentar el horno a 190ºC / 375ºF / gas 5.Mezcle la mitad del parmesano, el mascarpone, el taleggio, la ralladura de limón y el jugo, y las nueces.Ponga 1/4 de la mezcla a un lado, luego combine la mezcla de queso restante con la espinaca y sazone al gusto. Freír las hojas de salvia en mantequilla caliente y desmenuce 1/2 en la mezcla de queso y espinacas, guardando el resto para la parte superior.Ponga una buena cucharada de la mezcla de queso y espinacas a lo largo de uno de los bordes más largos de cada hoja de lasaña y enrolle.Póngalos en un plato de horno plano, salpique con la mezcla de queso sobrante, rocíe ¼ de un vaso de agua y espolvoree con el parmesano restante y las hojas crujientes de salvia. Cubra con papel de aluminio y hornee en el horno precalentado durante 20 minutos',
                tiempo: 40,
                precio: 150,
                estrellas: 4.3,
                video: video1,
                categoria: 'Recomendados',
              },
              {
                id: 2,
                img: image2,
                title: 'Pechuga de pollo asada con tomates cherry y espárragos',
                author: 'Enrique Gonzales',
                descripcion: 'No espere más a que venga la familia para disfrutar de un asado. Esta mini versión es genial cualquier día de la semana. Para una persona, dificultad: "súper fácil".',
                ingredientes: '1 pechuga de pollo de mayor bienestar.8 palitos de espárragos, recortados.6 tomates cherry.2 ramitas de romero.1 pizca de sal marina.1 pizca de pimienta negra recién molida.aceite de oliva.vino blanco.vinagre balsámico',
                receta: 'Precalentar el horno a 200 ° C / 400 ° F / gas 6. Ponga 1 pechuga de pollo, con su piel puesta, en un recipiente. Agregue 8 palos recortados de espárragos, 6 tomates cherry a la mitad y las hojas de 1 ramita de romero fresco más una ramita completa de romero también. Mezcle todo junto con una pizca de sal marina y pimienta negra recién molida y un chorrito de aceite de oliva. Coloque las verduras en una bandeja de papel de aluminio y coloque la ramita de pollo y romero encima. Sazonar bien Agregue un poco de vino blanco y cocine en el medio del horno de 25 a 35 minutos. Servir rociado con vinagre balsámico',
                tiempo: 40,
                precio: 170,
                estrellas: 3.5,
                video: video1,               
                categoria: 'Recomendados',
              },
              {
                id: 3,
                img: image3,
                title: 'Pasta al pesto',
                author: 'Utilísima',
                descripcion: 'Fideos deliciosos, con ajo y pollo al romeo. A todo el mundo le gusta la pasta al pesto. Agregar el pollo y las judías verdes hace que la cena se vuelva espectacular. Para 4 porciones, dificultad: "súper fácil".',
                ingredientes: '2 x 200 g de pechugas de pollo de corral sin piel.1 cucharadita de semillas de hinojo.2 ramitas de romero fresco.2 cucharadas de aceite de colza.4-5 dientes de ajo.1-2 chiles rojos frescos.8 tomates cherry maduros.PASTA Y PESTO.250 g de judías verdes.1 gran manojo de albahaca fresca.50 g de almendras blanqueadas.50 g de queso parmesano, más extra para servir.2 cucharadas de aceite de oliva virgen extra.1 limón.1 diente de ajo.300 g de hojas frescas de lasaña.200 g de espinaca baby',
                receta: 'En una hoja grande de papel resistente a la grasa, mezcle el pollo con sal marina, pimienta negra, semillas de hinojo y las hojas de romero. Dobla sobre el papel, luego golpea y aplana el pollo hasta 1,5 cm de grosor con un rodillo.Pon el pollo en la sartén con el aceite de colza, los dientes de ajo sin pelar y los chiles a la mitad, volteándolos después de 3 o 4 minutos, hasta que estén dorados y cocidos.Alinee los granos y corte los tallos, colóquelos en la cazuela, cúbralos con agua hirviendo con sal y cocínelos durante 6 minutos con la tapa puesta.Escoge unas hojas de albahaca para adornar, luego arranca los tallos y coloca el resto del racimo en el procesador con las almendras, parmesano, aceite de oliva virgen extra y jugo de limón.Aplasta el ajo sin pelar a través de una trituradora de ajo. Blitz hasta que esté suave, agregue un cucharón o dos de agua de cocción de los granos para aflojar, luego sazone al gusto.Cortar las hojas de lasaña en formas de pañuelos al azar y agregar a los frijoles para cocinar durante un par de minutos. Corta a la mitad o separa los tomates, agrégalos al pollo y agita la sartén.Revuelva la espinaca en la fuente de pasta, luego drene, reservando una taza llena de agua de cocina con almidón. Regrese la pasta, los frijoles y la espinaca a la sartén, vierta el pesto del procesador y mezcle, aflojando con salpicaduras de agua de cocción hasta que quede sedoso.Cortar las pechugas de pollo por la mitad y servir con los tomates y el chile en una cuchara sobre la parte superior. Rallar finamente un poco de queso parmesano extra sobre la pasta, luego espolvorear todo con hojas de albahaca',
                tiempo: 15,
                precio: 100,
                estrellas: 4.0,
                video: video1,                
                categoria: 'Recomendados',
              },
              {
                id: 4,
                img: image4,
                title: 'Bruschetta de Gennaro',
                author: 'El dragón - Gourmet',
                descripcion: 'Plato delicioso con verduras asadas. Esta bruschetta también va muy bien con carne y pescado. Para una persona, dificultad: "súper fácil".',
                ingredientes: '1 rebanada de pan de masa fermentada.1 pedazo de nabo asado.2 piezas de remolacha asada.1 pieza de pastinaca asada.sal marina.pimienta negra recién molida.aceite de oliva virgen extra.vinagre balsámico.1 diente de ajo, sin pelar y reducido a la mitad.2 ramitas de perejil fresco de hoja plana.1 puñado de hojas de ensalada mixta, lavadas e hiladas en seco.1 ramita de menta.fresca, hojas recogidas.1 limón.queso parmesano',
                receta: 'Siempre y cuando tenga un poco de ajo crudo para frotar sobre el pan tostado y un buen aceite de oliva, puede hacer bruschetta. Cualquier cosa que pongas encima después de eso, de carne sobrante, mariscos o incluso anchoas simples, será delicioso. Uno de mis combos favoritos es el cordero sobrante, menta fresca y un chorrito de vinagre de jerez ... ¡vamos!.Estos bruschetta de vegetales tostados son deliciosos y fáciles. Todo lo que tiene que hacer es sazonar y vestir los vegetales tostados sobrantes con cuidado para que vuelvan a la vida y tenga un refrigerio perfecto o un almuerzo ligero.Coloque el pan en una sartén caliente y tápelo en ambos lados. Mientras esto sucede, use la parte posterior de un tenedor o cuchillo para mezclar aproximadamente las verduras en una tabla de madera. Sazone con sal y pimienta, rocíe un poco de aceite de oliva virgen extra y un poco de balsámico, luego revuelva. Una vez que el pan tenga marcas agradables de carbonilla en ambos lados, frote el diente de ajo cortado sobre el sabor y luego ponga las verduras en puré encima. Picar finamente el perejil y esparcirlo encima.Mezcle la ensalada y las hojas de menta en un bol con una buena pizca de sal, un chorrito de aceite de oliva virgen extra, un chorrito de balsámico y un chorrito de jugo de limón. Coloque una pizca de hojas de ensalada encima de la bruschetta y luego raspe con un parmesano. Termine con un chorrito de aceite de oliva virgen extra y sirva inmediatamente con el resto de la ensalada en el lateral',
                tiempo: 15,
                precio: 175,
                estrellas: 3.6,
                video: video1,               
                categoria: 'Recomendados',
              },
              {
                id: 5,
                img: image5,
                title: 'Alitas de pollo: estilo agridulce',
                author: 'Jamie Oliver',
                descripcion: 'Alitas de pollo dulces y deliciosas con espléndido glaseado de miel. Este es un plato muy simple que invierte en grandes sabores, por lo que sólo necesita una bruschetta a la parrilla y cebollas cortadas en vinagre para servir. Rinde entre 4/6, dificultad: "no tan complicado".',
                ingredientes: '4 dientes de ajo.3 cebollas rojas grandes.1 chile rojo fresco.16 alas de pollo al aire libre.1 pequeño puñado de pasas.aceite de oliva.1 x 400 g de lata de tomates de ciruela de calidad.vinagre balsámico.miel líquida.2 ramitas de romero fresco',
                receta: 'Precalentar el horno a 170ºC.Pele y pique finamente el ajo y la cebolla, luego pique y corte finamente la guindilla.Coloque 2 hojas grandes de papel de aluminio y apile las alitas de pollo en el medio. Sazonar con una buena pizca de sal marina y pimienta negra, juntar los lados de la lámina para hacer un tazón grande, agregar un chorrito de agua y luego frotar todos los bordes de la lámina para hacer un paquete.Haga estallar el paquete en una bandeja para hornear y cocine en el horno durante 45 minutos, o hasta que el pollo esté tiernamente tierno y la carne se separe fácilmente del hueso.Mientras tanto, haz tu glaseado. Remoje las pasas en una taza de agua hirviendo y déjelas a un lado.Caliente un trozo de aceite en una sartén grande a fuego medio, agregue el ajo, el chile y la mayoría de la cebolla rebanada, guardando un puñado pequeño para más adelante. Cocine por 10 a 15 minutos, o hasta que todo esté suave y pegajoso.Incline las pasas, el agua en remojo y los tomates enlatados, y divídalos con una cuchara.Deje burbujear durante 10 a 15 minutos, o hasta que se espese, luego agregue 4 cucharadas soperas de vinagre balsámico y miel. Tómese su tiempo y no se sienta tentado a cocinarlo demasiado rápido, ¡valdrá la pena!Sazone con sal y pimienta, luego agregue la mezcla a una licuadora (o use una batidora) para suavizar el glaseado. No te vuelvas loco ya que un poco de textura en el vidriado es bueno.En un tazón, machaque las rodajas de cebolla restantes con una pizca de sal y un buen chorrito de vinagre y déjelas a un lado: esto suavizará las cebollas y agregarán una increíble nitidez para cortar la dulzura de la deliciosa y oscura, pegajosa y brillante vidriado.Comprueba que las alitas de pollo estén tiernas a tu gusto. Calentar un trozo de aceite en una sartén grande a fuego alto, recoger las hojas de romero y freír hasta que estén crujientes, luego transferir a un plato pequeño para más tarde.Mantenga la sartén caliente, agregue las alas y fría hasta que estén doradas. Agregue el glaseado y siga girando las alas para cubrirlas (en este punto puede agregar una llovizna extra de miel, si le gustan las alas extra pegajosas).Disperse con las cebollas encurtidas rápidas y el romero crujiente, ¡entonces enganche! Delicioso servido con bruschetta a la plancha, si quieres',
                tiempo: 75,
                precio: 150,
                estrellas: 3.7,
                video: video1,                
                categoria: 'Recomendados',
              },
              {
                id: 6,
                img: image6,
                title: 'Ensalada César de pollo asado',
                author: 'Narda Lepes',
                descripcion: 'Lleve su ensalada de pollo César a la próxima galaxia poniendo el pollo en salmuera durante la noche, lo que agregará un montón de sabor, jugosidad y caramelización, y asando sus crotones en los jugos del pollo para la textura y sabor final. Rinde entre 10 y 12, dificultad: "para presumir".',
                ingredientes: '2,5 kg de pollo entero de corral.400 g de pan de masa fermentada.aceite de oliva.1 diente de ajo.50 g de estaño de anchoas en aceite, de fuentes sostenibles.1 manojo de perejil fresco de hoja plana, (30g). 2 chiles rojos frescos. aceite de oliva virgen extra. 1 limón. 4 lechugas romanas. 150 g de rábanos de color mezclado. 1 pepino. ½ un montón de cebolletas frescas, (15g). SALMUERA. 4 cucharadas de pimienta negra. 4 cucharadas de semillas de hinojo. 2 litros de jugo de manzana fresca. 100 g de sal marina. ½ un manojo de tomillo fresco, (15g). 12 hojas frescas de laurel. 6 chiles rojos secos. ADEREZO CÉSAR. 50 g de queso parmesano, más extra para servir. 1 cucharadita de mostaza inglesa. 2 cucharaditas de salsa Worcestershire. 250 g de yogur griego. 1 limón',
                receta: 'Para la salmuera, tuesta los granos de pimienta y las semillas de hinojo en una olla grande a fuego alto durante 1 minuto, luego agregue el jugo de manzana, sal marina, tomillo y la bahía.Revuelva en los chiles secos y deje que hierva, luego retírelo del fuego, rellene con 1 litro de agua fría y luego deje que se enfríe completamente.Use un cuchillo afilado para cortar con cuidado la parte posterior del pollo para que pueda abrirlo y luego agregarlo a la salmuera enfriada (transfiéralo a un recipiente más grande, si es necesario).Cubra con film transparente y déjelo en la nevera durante al menos 12 horas, luego drene y seque con papel de cocina.Precalentar el horno a 200ºC / 400ºF / gas 6.Rompa la masa madre en trozos grandes y déjela a un lado. Frote 1 cucharada de aceite de oliva por todo el pollo y colóquelo directamente sobre las barras del horno, con la piel hacia arriba, y coloque una bandeja grande exactamente debajo para atrapar los jugos deliciosos.Tueste por 30 minutos, luego baje el horno a 160ºC / 325ºF / gas 3. Agregue la masa madre a los jugos en la bandeja, luego rompa el bulbo de ajo y esparza los dientes sin pelar, luego mezcle todo para cubrir.Asar durante 1 hora, o hasta que el pollo esté dorado y bien cocido, tirando ocasionalmente los crutones de masa fermentada para cocinar uniformemente. Deje que el pollo descanse durante 30 minutos antes de tallar.Escurra las anchoas (guardando el aceite) y corta por la mitad a lo largo, luego coloca el plato en forma cruzada.Pica finamente los tallos de perejil, reservando las hojas para después. Cortar finamente la guindilla y esparcir sobre las anchoas, junto con los tallos de perejil. Rocíe con ½ cucharada sopera de cada aceite de oliva de anchoa y aceite de oliva virgen extra, luego ralle finamente la mitad de la ralladura de limón y exprima la mitad del jugo. Déjalo marinar. Para el aderezo César, ralla finamente el parmesano en un bol, agrega la mostaza, la salsa Worcestershire y el yogur, luego bate para combinar.Exprima el jugo de limón, vierta 8 cucharadas de aceite de oliva virgen extra y vuelva a mezclar. Pruebe y sazone a la perfección, aflojando con un chorrito de agua, si es necesario.Corta las lechugas y los rábanos y raspa un tenedor por los lados del pepino. Cortar finamente los rábanos, el pepino, las hojas de perejil y el cebollín, cortar la lechuga aproximadamente y colocar todo en un tazón grande.Coloque el pollo y la mitad de los crotones de ajo en una tabla. Agregue los crotones restantes al tazón de ensalada, vierta más de la mitad del aderezo y mezcle todo.Afeitarse un poco de parmesano con un pelador de velocidad, luego llevar a la mesa con las anchoas marinadas, pollo, crutones extra y aderezo. Deje que todos caven y construyan su propia ensalada César.',
                tiempo: 105,
                precio: 130,
                estrellas: 3.3,
                video: video1,                
                categoria: 'Recomendados',
              },
              {
                id: 7,
                img: image7,
                title: 'Pan de queso y ajo',
                author: 'Osvaldo Gross',
                descripcion: 'Receta para lograr un pan de queso y ajo riquísimo. Rinde entre 4 y 6 personas, dificultad: "no tan complicado".',
                ingredientes: '2 bulbos de ajo.aceite de oliva virgen extra.25 g de queso parmesano.1 x 125 g de bola de mozzarella.50 g de queso azul.1/2 un manojo de albahaca fresca.80 g de mantequilla sin sal, (a temperatura ambiente).MASA.450 g de harina de pan blanco sin gluten, más extra para espolvorear.2 cucharaditas de levadura de acción rápida.1 cucharadita de polvo de hornear sin gluten.1 cucharada de azúcar.1 cucharadita de sal marina.1 huevo grande de gallinas camperas.1 clara de huevo grande de gallinas camperas.1 cucharadita de vinagre de vino blanco',
                receta: 'Calentar el horno a 200ºC.Corta la parte superior de los bulbos de ajo, exponiendo los dientes. Coloque en un cuadrado de 20 cm de hoja de estaño, rocíe con 1 cucharada de aceite, luego envuelva la lámina alrededor de ellos.Coloque en una bandeja para hornear y cocine por 45 minutos, o hasta que esté muy suave. Dejar enfriar un poco, luego exprimir el ajo de sus pieles.Mientras espera, engrase y forme una lata de pan de 1,2 litros con pergamino.Rallar finamente el parmesano, escurrir y desmenuzar la mozzarella, desmenuzar el Stilton, y recoger y rasgar las hojas de albahaca.Mezcle la mantequilla suave con todo menos 1 cucharada de cada queso. Agregue la albahaca, más una pizca de sal marina y pimienta negra. Dejar de lado.Agregue la harina, la levadura, el polvo de hornear, el azúcar y la sal en un tazón grande. En otro tazón, bata el huevo entero y la clara de huevo con el vinagre.Vierta los huevos y 325ml de agua tibia sobre la mezcla de harina, revolviendo con una cuchara de madera hasta que forme una masa suave.Forme una bola suave, agregue un poco de harina si es necesario, luego déjela a un lado durante 20 minutos para reafirmarla.Divida la masa en cuatro trozos, luego enrolle o presione cada uno en un rectángulo de aproximadamente 20 x 10 cm - necesitará usar mucha harina para evitar que la masa se adhiera tanto a usted como a la encimera.Coloca un tercio de la mantequilla con queso y unos dientes de ajo sobre la primera capa, repite con otros pedazos de masa, con mucho cuidado superponiéndolos. Termine con la última capa de masa.Corta la masa en capas a lo ancho en cuatro, luego gira cada pieza con el lado cortado hacia arriba y colócalas una al lado de la otra en la lata. Cúbralo con la película adhesiva engrasada y déjelo en un lugar cálido hasta que esté bien levantado, aproximadamente 1 hora. El pan se elevará aún más en el horno, así que asegúrese de que el pan haya llenado la lata y se sienta como una almohada antes de hornear.Precalentar el horno a 220C.Esparcir con el resto del queso, rociar con un poco de aceite, luego hornear por 45 minutos o hasta que se dore bien y chisporrotear. Coma caliente, en lugar de caliente, y el día en que está hecho.',
                tiempo: 110,
                precio: 120,
                estrellas: 4.2,
                video: video1,                
                categoria: 'Recomendados',
              },
              {
                id: 8,
                img: image8,
                title: 'Tacos de pescado mexicano',
                author: 'Enrique Olvera',
                descripcion: 'Increíbles tacos de pescado con todos los adornos: guacamole grueso, salsa de piña dulce, crema agria de ajo y un repollo con jalapeño. Sirve a 4, dificultad: "no tan complicado".',
                ingredientes: '1 x 400 g de lata de frijoles cannellini.8 tortillas de harina de gran calidad.aceite de oliva.4 x 200 g de filetes de eglefino, pelados, escamados, deshuesados, de fuentes sostenibles.1 limón.algunas ramitas de menta fresca.SALSA DE AJO BLANCO.1 bulbo de ajo.150 g de crema agria.1 lima.unas ramitas de perejil fresco de hoja plana.SALSA DE PIÑA.1 pequeña piña fresca.2 chiles frescos, colores mezclados si es posible.1/2 un montón de menta fresca, (15g).1 cebolla roja pequeña.2 limas.aceite de oliva virgen extra.GUACAMOLE.1/2 una pequeña cebolla roja.2 cebollas de primavera.1-2 chiles rojos frescos.3 aguacates maduros.2 tomates maduros.algunas ramitas de menta fresca.1 lima.ENSALADA DE COL.1/2 una col roja.1 chile verde fresco de jalapeño.1 cucharada de vinagre de vino tinto',
                receta: 'Precalentar el horno a 180ºC.Coloque todo el bulbo de ajo en el horno durante 1 hora o hasta que se ablande.Para hacer la salsa de piña, corte y pele la piña, cortando cualquier trozo marrón.Cortar en rodajas, cortar y descartar el núcleo duro.Freír en una sartén grande a fuego medio durante unos 4 minutos, o hasta que esté chamuscado, volteándolo ocasionalmente. Picar finamente, luego colocar en un bol con todos los jugos encantadores.Pique finamente los chiles, pique y pique finamente las hojas de menta, luego pele y pique finamente la cebolla. Exprima el jugo de lima y rocíe con aceite de oliva virgen extra. Sazone al gusto.Para el guacamole, pele y corte aproximadamente la cebolla roja, corte y corte aproximadamente las cebolletas y corte los chiles en una tabla de cortar grande. Destone los aguacates y coloque la carne en el tablero, luego divida a la mitad y elimine los tomates.Comience a cortar y mezclar todos los ingredientes hasta que estén finamente picados y combinados.Elija las hojas de menta, exprima el jugo de lima y rocíe con 1 cucharada de aceite de oliva virgen extra. Sazone al gusto con sal marina y pimienta negra, dándole un chuleta final.Corta muy finamente el repollo rojo en una mandolina (¡usa el protector!). Cortar finamente el chile jalapeño, luego colocar en un bol con el vinagre. Mezclar bien.Exprime los dientes de ajo tostados de sus pieles, luego machaca y dobla a través de la crema agria (usa yogur natural si quieres estar un poco más saludable). Agregue el jugo de lima y un chorrito de aceite de oliva virgen extra, luego sazone al gusto. Escoja, pique finamente y revuelva a través de las hojas de perejil.Escurrir y agregar los frijoles cannellini a una sartén mediana a fuego medio-alto. Cocine de 5 a 7 minutos, o hasta que empiecen a reventar y formar ampollas. Coloque en un recipiente y manténgalo caliente. Envuelva y caliente sus tortillas en el horno de enfriamiento.Limpie la sartén y vuelva a calentar a fuego medio con un chorrito de aceite de oliva. Sazone los filetes de eglefino y ralle finamente sobre la ralladura de limón, luego coloque el lado de la piel hacia abajo en la sartén durante 4 minutos, presionando ligeramente con una rebanada de pescado. Déles la vuelta y cocínelos por otros 3 minutos, o hasta que estén ligeramente dorados y recién cocinados.Coloque sus tortillas calientes en un plato y cubra con una cucharada de guacamole y repollo. Agrupe el pescado en trozos gruesos, luego cubra con la salsa de piña, una cucharada de crema agria y una cucharada de frijoles crujientes.Escoja, corte finamente y esparza sobre las hojas de menta, luego sirva con rodajas de chile rojo y rodajas de lima, si lo desea.',
                tiempo: 85,
                precio: 160,
                estrellas: 3.9,
                video: video1,               
                categoria: 'Recomendados',
              },
              {
                id: 9,
                img: image9,
                title: 'Tarta primavera',
                author: 'Mauro Colagreco',
                descripcion: 'Tocino rayado, espinacas y puerros en masa filo. Ideal para prepararlo junto a los chicos ya que es un plato muy desordenado y en donde "se tira todo". Sirve a 6, dificultad: "súper fácil".',
                ingredientes: 'aceite de oliva.1 paquete de 270 g de pasta filo.200 g de espinaca baby.6 lonchas de tocino rayado ahumado de alto bienestar.6 huevos grandes de gallinas camperas.200 ml de leche.1 cucharadita de polvo de mostaza.1/2 un montón de cebolletas frescas, (15g).1 limón.3 puerros medianos',
                receta: 'Precaliente el horno a 180 ° C / 350 ° F / gas 4. Engrase ligeramente un molde para hornear de 20 cm x 30 cm con aceite.Haga que los niños lo ayuden a cubrir la fuente para hornear con una capa de masa, dejando que los bordes sobresalgan ligeramente. Cepille con un poco de aceite, luego agregue otra capa de masa, repitiéndola hasta que la haya usado todo (debe haber 3 o 4 capas).Hervir el hervidor de agua, colocar la espinaca en un colador y verter sobre el agua caliente para marchitarla (puede que tenga que hacer esto en 2 lotes). Empuja la espinaca hacia abajo con la parte posterior de una cuchara, luego, cuando esté lo suficientemente fría como para manejarla, haz que los niños exprimen el exceso de agua con las manos. Coloque la espinaca en una tabla y corte aproximadamente, luego colóquela en un tazón grande y déjela a un lado.Coloque la parrilla en alto y ase el tocino hasta que esté crujiente, luego póngalo a un lado para que se enfríe.Batir los huevos en un tazón grande con una pizca de sal marina y pimienta negra. Batir la leche y la mostaza en polvo, cortar el cebollino y rallar con la ralladura de limón.Haga que los niños desmenucen el tocino frío en la espinaca y luego corte, corte y agregue los puerros. Mezclar bien y dispersar en la caja de pasta filo. Vierta sobre la mezcla de huevo y coloque cuidadosamente el plato en el fondo del horno.Hornee de 30 a 40 minutos o hasta que estén listos. Deje que el pastel se enfríe durante 20 minutos antes de cortarlo. Delicioso servido con una fresca ensalada verde.',
                tiempo: 55,
                precio: 180,
                estrellas: 4.0,
                video: video1,               
                categoria: 'Recomendados',
              },
              {
                id: 10,
                img: image10,
                title: 'Sushi de espárragos',
                author: 'El dragón - Gourmet',
                descripcion: 'Ingredientes preparados para que puedas cocinar sushi. Delicioso sushi con aguacate y salsa de lima. Para 24 piezas, dificultad: "no tan complicado".',
                ingredientes: '80 g de arroz de sushi.1/2 una pequeña cabeza de brócoli.1 gran puñado de col rizada.1 aguacate maduro.salsa de soja baja en sal.1 cucharadita de pasta de wasabi.2 limas.1 cucharada de miel líquida.1 cm de jengibre.120 g de salmón ahumado en caliente, de fuentes sostenibles.50 g de brotes de guisantes o 20 g de berro',
                receta: 'Cocine el arroz de acuerdo con las instrucciones del paquete.Corte el brócoli en florecillas, luego cocine a vapor con la col rizada en un recipiente de vapor sobre el arroz hasta que esté tierno. Refresque bajo agua corriente fría.Transfiere el arroz y las verduras a tu lonchera.Divida a la mitad y destone el aguacate, luego use un tenedor para machacar la carne en su piel. Agregue un poco de salsa de soja, la pasta de wasabi y el jugo de 1 lima.Mantenga el aguacate enriquecido en su piel y úselo como un recipiente. Cubra con clingfilm (si está alimentando a un amigo en el trabajo, simplemente junte las mitades), y póngalo en su lonchera.Para un aderezo, vierta 1 cucharada de salsa de soya en un tarro de mermelada, agregue el jugo de la lima restante y la miel. Pelar y rallar en el jengibre.Ponga el salmón sobre el arroz y las verduras y espolvoree los brotes de guisantes o el berro en la parte superior.Mantenga su lonchera, el aderezo y el aguacate refrigerados hasta que esté listo para comer, luego agite el aderezo y vierta sobre el arroz y el salmón, mezcle para cubrir y disfrute, con el aguacate al lado.',
                tiempo: 45,
                precio: 200,
                estrellas: 3.7,
                video: video1,
                categoria: 'Recomendados',
              },
              {
                id: 11,
                img: image11,
                title: 'Pollo y papas fritas mediterráneas',
                author: 'Utilísima',
                descripcion: 'Preciosas patas de pollo con limón y papas nuevas trituradas, todo cocinado en una bandeja: es una cena sencilla y satisfactoria, y los sabores herbales traerán un poco de sol a la mesa. Para 4 personas, dificultad: "no tan complicado".',
                ingredientes: '1 limón.4 patas de pollo de corral.1 kg de papas nuevas.4 ramitas de romero fresco.1 manojo de tomillo fresco.2 hojas frescas de laurel.aceite de oliva.100 g de aceitunas verdes sin hueso',
                receta: 'Precalentar el horno a 180ºC.Cortar el limón longitudinalmente en cuartos y colocar en una lata grande para asar con las patas de pollo, patatas nuevas y todas las hierbas. Mezcle en 1 a 2 cucharadas de aceite, sazone bien y tueste durante 45 minutos.Retire la bandeja del horno. Cuidadosamente exprime las rodajas de limón asadas sobre todo, aplastando algunas de las papas para que revienten - esto te da un área de superficie más grande para que absorban mucho sabor y se vuelvan agradables y crujientes.Agregue las aceitunas, revuelva todo y tueste por otros 15 minutos, o hasta que el pollo esté cocido y las papas estén doradas.Retirar del horno y servir: esto es delicioso con un puñado de berros en el costado.',
                tiempo: 60,
                precio: 200,
                estrellas: 3.2,
                video: video1,
                categoria: 'Recomendados',
              },
              {
                id: 12,
                img: image12,
                title: 'Ensalada de sushi simple',
                author: 'El dragón - Gourmet',
                descripcion: 'Con salmón ahumado, aguacate y col rizada. Rinde para 2 porciones, dificultad: "no tan complicado".',
                ingredientes: '80 g de arroz de sushi.1/2 una pequeña cabeza de brócoli.1 gran puñado de col rizada.1 aguacate maduro.salsa de soja baja en sal.1 cucharadita de pasta de wasabi.2 limas.1 cucharada de miel líquida.1 cm de jengibre.120 g de salmón ahumado en caliente, de fuentes sostenibles.50 g de brotes de guisantes o 20 g de berro',
                receta: 'Cocine el arroz de acuerdo con las instrucciones del paquete.Corte el brócoli en florecillas, luego cocine a vapor con la col rizada en un recipiente de vapor sobre el arroz hasta que esté tierno. Refresque bajo agua corriente fría.Transfiere el arroz y las verduras a tu lonchera.Divida a la mitad y destone el aguacate, luego use un tenedor para machacar la carne en su piel. Agregue un poco de salsa de soja, la pasta de wasabi y el jugo de 1 lima.Mantenga el aguacate enriquecido en su piel y úselo como un recipiente. Cubra con clingfilm (si está alimentando a un amigo en el trabajo, simplemente junte las mitades), y póngalo en su lonchera.Para un aderezo, vierta 1 cucharada de salsa de soya en un tarro de mermelada, agregue el jugo de la lima restante y la miel. Pelar y rallar en el jengibre.Ponga el salmón sobre el arroz y las verduras y espolvoree los brotes de guisantes o el berro en la parte superior.Mantenga su lonchera, el aderezo y el aguacate refrigerados hasta que esté listo para comer, luego agite el aderezo y vierta sobre el arroz y el salmón, mezcle para cubrir y disfrute, con el aguacate al lado.',
                tiempo: 35,
                precio: 130,
                estrellas: 3.5,
                video: video1,
                categoria: 'Recomendados',
              },
              {
                id: 13,
                img: image13,
                title: 'Insanity burger',
                author: 'Jamie Oliver',
                descripcion: 'Con mostaza y salsa de hamburguesa casera, utiliza la técnica de cepillar las hamburguesas con mostaza y un chorrito de salsa Chipotle de Tabasco mientras se cocinan para formar una increíble capa de condimento. Rinde para 4, dificultad: "súper fácil".',
                ingredientes: '800 g de filete de carne picada.aceite de oliva.1 cebolla roja grande.1 toque de vinagre de vino blanco.2 pepinillos grandes.4 bollos de hamburguesas brioche con tapa de sésamo.4-8 lonchas de tocino rayado ahumado de mayor bienestar.4 cucharaditas de mostaza americana.Salsa de chipotle tabasco.4 rodajas finas de queso Red Leicester.4 cucharaditas de ketchup de tomate.SALSA DE HAMBURGUESA.1/4 de una lechuga iceberg.2 cucharadas colmadas de mayonesa.1 cucharada colmada de salsa de tomate.1 cucharadita de salsa Tabasco Chipotle.1 cucharadita de salsa Worcestershire.1 cucharadita de brandy, o bourbon (opcional)',
                receta: 'Para obtener la mejor hamburguesa, vaya a su carnicería y pídales que se tomen 800 g de filete para chuletón para usted; este corte tiene un equilibrio realmente bueno de grasa y carne sabrosa.Divídalo en 4 y, con las manos mojadas, enrolle cada pieza en una bola, luego presione en empanadas planas de aproximadamente 12 cm de ancho y aproximadamente 2 cm más anchas que sus panecillos. Coloque en un plato engrasado y enfríe en la nevera.A continuación, corte finamente la cebolla roja, luego póngala en un bol con el vinagre y una pizca de sal marina. Corta los pepinillos y divide los bollos a la mitad. Pique finamente la lechuga y mezcle con el resto de los ingredientes de la salsa de hamburguesa en un tazón, luego sazone al gusto.Solo me gusta cocinar 2 hamburguesas a la vez para lograr la perfección, así que llévate dos sartenes sobre la marcha: una sartén antiadherente grande a fuego alto para tus hamburguesas y otra a fuego medio para el tocino.Amasar las hamburguesas con aceite y condimentarlas con sal y pimienta. Pon 2 hamburguesas en la primera sartén, presionándolas con una rebanada de pescado, luego coloca la mitad del tocino en la otra sartén.Después de 1 minuto, voltee las hamburguesas y cepille cada lado cocido con ½ cucharadita de mostaza y un chorrito de Tabasco. Después de otro minuto, voltee al lado de la mostaza y vuelva a cepillar con otra ½ cucharadita de mostaza y una segunda dosis de Tabasco en el otro lado.Cocine por un minuto más, en ese momento puede colocar un tocino crujiente encima de cada hamburguesa con una rebanada de queso. Agregue un pequeño chorrito de agua a la sartén y coloque un tazón resistente al calor sobre las hamburguesas para derretir el queso - 30 segundos deberían hacerlo.Al mismo tiempo, tueste 2 bollos partidos en la grasa del tocino en la otra sartén hasta que estén ligeramente dorados.Repita con las dos hamburguesas restantes.Para preparar cada hamburguesa, agregue un cuarto de la salsa de hamburguesa a la base del bollo, luego cubra con una hamburguesa de bacon cursi, una cuarta parte de las cebollas y los pepinillos. Frote la parte superior del moño con una cucharadita de ketchup, luego presione suavemente juntos.A medida que la hamburguesa descansa, los jugos se empaparán en el moño, así que sirva enseguida, lo cual es genial, o para una experiencia más asquerosa, envuélvalos en papel resistente a las grasas y luego déle un minuto para irse espléndida y descuidada',
                tiempo: 35,
                precio: 120,
                estrellas: 3.5,
                video: video1,
                categoria: 'Los más comprados',
              },
              {
                id: 14,
                img: image14,
                title: 'Las papas perfectas',
                author: 'Maru Botana',
                descripcion: 'Las papas fritas o patatas fritas, también conocidas como papas a la francesa o patatas a la francesa, son las papas que se preparan cortándose en rodajas o en forma de bastones y friéndolas en aceite caliente hasta que queden doradas, retirándolas del aceite y luego sazonándolas con sal. Para 4 personas, dificultad: "no tan complicado"',
                ingredientes: '800 g de papas.aceite de girasol',
                receta: 'Tres cosas obvias son importantes en su viaje a la perfección: su elección de papa, su elección de aceite y su elección de sal.El aceite, el girasol y la semilla del sol son muy eficientes, y muchas personas juran que usan aceite de cacahuete. Pero, si buscas sabor, cocinar chips en sebo de res (grasa de res representada que puedes obtener de tu carnicero) te da mejor sabor y color: la elección es tuya.Por lo tanto, para el negocio: cortar 800 g de patatas en trozos del tamaño de un dedo, dejando la piel puesta - no seas tan exacto.Las tiendas de chips tienen freidoras industriales masivas, que no puedes recrear en casa, por lo que necesitas utilizar una sartén grande y resistente a fuego medio-alto (a menos que tengas una freidora de grasa, por supuesto). Su aceite debe tener 8 cm de profundidad, pero nunca llene su sartén más de la mitad. Si no tiene un termómetro, use un chip en bruto, y cuando comience a flotar y fríe, la temperatura debería ser de aproximadamente 140 ° C, lo que es perfecto para escaldar.Use un tamiz de metal grande para bajar suavemente las virutas en la sartén durante aproximadamente 8 minutos, o hasta que estén blandas, pero sin color, y luego retírelas a una bandeja para que se enfríen.Encienda la calefacción debajo del aceite y vuelva a colocar una viruta blanqueada en el aceite como una guía. Una vez que esté flotando y dorado, la temperatura debería ser de aproximadamente 180 ° C, lo que es perfecto para freír y le dará chips con esos crujientes exteriores importantes y suaves medios.En esta etapa, es posible que desee cocinar sus chips en tandas de 2 porciones, para que no disminuya demasiado la temperatura del aceite ni atempere la bandeja. Freír las patatas fritas hasta que estén doradas, luego retirar a un recipiente con papel de cocina, batir un poco, sazonar con sal marina y servir de inmediato.',
                tiempo: 40,
                precio: 110,
                estrellas: 4.3,
                video: video1,
                categoria: 'Los más comprados',
              },
              {
                id: 15,
                img: image15,
                title: 'Pizza básica',
                author: 'Donato De Santis',
                descripcion: 'Deliciosa masa y cobertura. Una vez que vean lo simple y sabrosa que es esta receta de masa de pizza, no querrán comida para llevar. Sirve 8 porciones, dificultad: "súper fácil".',
                ingredientes: '800 g de harina de pan blanco.200 g de harina de sémola molida fina o harina de pan blanco fuerte.1 cucharada de sal fina de mar.2x7 g sobres de levadura seca.1 cucharada de azúcar en polvo de oro.SALSA DE TOMATE (4 PIZZAS).1 diente de ajo.1 manojo de albahaca fresca.aceite de oliva.1 x 400 g de lata de tomates de ciruela de calidad.TOPPING (4 PIZZAS).85 g de queso mozzarella',
                receta: 'Para la masa, amontona las harinas y 1 cucharadita rasa de sal marina sobre una superficie limpia y haz un pozo en el centro.Agregue la levadura y el azúcar a 650 ml de agua tibia, mezcle y deje por unos minutos, luego vierta en el pozo.Usando un tenedor y un movimiento circular, lentamente traiga la harina del borde interno del pozo y mezcle con el agua. Continúa mezclando, trayendo toda la harina: cuando la masa se junta y se vuelve demasiado dura para mezclarla con el tenedor, enharina las manos y comienza a darle vueltas como una pelota.Amasar la masa rodándola hacia atrás y hacia adelante, usando las manos para estirar, tirar y empujar la masa. Siga amasando durante 10 minutos, o hasta que tenga una masa suave, elástica y suave.Coloque la masa en un recipiente ligeramente engrasado, cubra con film transparente y déjelo en un lugar tibio para comprobar durante 45 minutos o hasta que duplique su tamaño.Para la salsa, pele y corte finamente el ajo, luego recoja las hojas de albahaca y pique finamente los tallos.Caliente 1 cucharada de aceite en una sartén a fuego medio-bajo, agregue el ajo y los tallos de albahaca, luego cocine suavemente por un par de minutos, o hasta que el ajo esté ligeramente dorado, luego agregue la mayoría de las hojas de albahaca, los tomates, y una pizca de sal y pimienta.Deje la salsa para marcar durante unos 20 minutos, o hasta que quede suave, separando los tomates con una cuchara de madera. Cuando se acabe el tiempo, saboree y sazone a la perfección.Para armar las pizzas, divide la masa por la mitad. Envuelve una mitad en film transparente y congélalo para otro día. Con la mitad restante, divida la masa en 4 bolas iguales.Harina cada bola de masa, luego cúbrala con film transparente y déjela reposar durante aproximadamente 15 minutos, esto hará que sea más fácil rodarla finamente.Espolvoree una superficie limpia y la masa con un poco de harina o sémola, y extiéndala en un círculo áspero, de aproximadamente 1/2 cm de grosor.Arranque una hoja de papel de aluminio del tamaño adecuado, frótela con aceite de oliva, aplique un polvo fino con harina o sémola y coloque la base de la pizza encima. Continúa haciendo lo mismo con la masa restante, espolvorea con un poco de harina para que puedas amontonarlos. Cubra con film transparente y colóquelo en el refrigerador.Cuando esté listo para cocinarlos, precaliente el horno a 250 ° C.En esta etapa puede aplicar su cobertura: extender la salsa de tomate sobre la base, extendiéndola hacia los bordes. Rompa la mozzarella y espolvoree con las hojas de albahaca restantes. Rocíe con un poquito de aceite de oliva y agregue una pizca de sal y pimienta.Si puede, cocine las pizzas en un trozo de granito en su horno convencional; si no, cocínelas una a una sobre trozos de papel de aluminio directamente sobre las barras del estante del horno, hacia el fondo del horno (si está va a cocinar sus pizzas en los barrotes del horno, asegúrese de que no sean demasiado grandes; de lo contrario, será difícil maniobrar). Cocine de 7 a 10 minutos, hasta que las pizzas estén doradas y crujientes.Estas son algunas de mis ideas favoritas: Mozzarella, anchoas, chile, alcaparras y perejil.Panceta ahumada, mozzarella, chile fresco y tomates.Huevo, jamón, alcachofas, aceitunas, mozzarella, salsa de tomate y albahaca.Uvas verdes y rojas, romero, piñones y ricotta.Patatas, mozzarella, romero, tomillo y tomates.Carne de cerdo desmenuzada a fuego lento con tomillo, Taleggio y cohete vestido de limón.Salami picante, calabacín, albahaca, tomate y mozzarella',
                tiempo: 80,
                precio: 200,
                estrellas: 4.3,
                video: video1,
                categoria: 'Los más comprados',
              },
              {
                id: 16,
                img: image16,
                title: 'Chocotorta',
                author: 'Maru Botana',
                descripcion: 'Delicioso postre, simple y rápido de hacer. Se logra utilizando chocolinas y una mezcla de dulce de leche y queso crema. Para compartir... o no, dificultad "súper fácil".',
                ingredientes: '500 gr de queso crema.500 gr de dulce de leche repostero.Cacao dulce c/n.Leche c/n.300 gr de chocolate semiamargo.300 ml de crema de leche.500 gr de galletas de chocolate',
                receta: 'Batir el dulce de leche con el queso crema hasta integrar.Preparar la chocolatada donde mojaremos nuestras galletas.Hacer una capa de galletas mojadas en chocolatada.Por encima colocar una capa de relleno.Hacer esto 3 veces más.Enfriar.Hacer la ganache: llevar la crema a primer hervor.Verterla sobre un bol con chocolate picado.Dejar reposar 5 minutos.Integrar la mezcla batiendo.Verterla sobre la torta.Enfriar 2 horas.',
                tiempo: 30,
                precio: 130,
                estrellas: 4.2,
                video: video1,
                categoria: 'Los más comprados',
              },
              {
                id: 17,
                img: image17,
                title: 'Estofado de carne',
                author: 'Utilísima',
                descripcion: 'Una receta de estofado de ternera tierna con una preparación mínima: ponerla en el horno enseguida y dejarla actuar de manera mágica. Para 6 personas, dificultad: "no tan complicado".',
                ingredientes: '800 g de carne de ternera magra.2 cucharadas de harina común.aceite de oliva.2 dientes de ajo.1 puñado de chalotes.2 palitos de apio.4 zanahorias.1/2 un manojo de tomillo fresco, (15g).4 tomates de vid maduros.150 ml de vino tinto.500 ml de caldo de carne orgánica.2 hojas frescas de laurel.Salsa Worcestershire',
                receta: 'Precalentar el horno a 160ºC.Corta la carne en trozos de 1 cm, luego échala en un bol con la harina, asegurándote de que los trozos de carne estén totalmente cubiertos. Dejar de lado.Agregue un chorrito de aceite a una cazuela grande y colóquelo a fuego medio. Cuando esté caliente, agregue la carne y cocine durante 5 minutos, o hasta que la carne esté dorada por completo. Transfiera a un plato y déjelo a un lado.Mientras la carne se cocina, pele y pique finamente el ajo, luego pele los chalotes y divida la mitad de ellos, manteniendo unos enteros. Recorte y corte aproximadamente el apio, luego pele, recorte y corte las zanahorias en rondas de 2 cm.Salpique un poco más de aceite en la sartén, luego agregue las verduras. Pele las hojas del tomillo y agregue a la sartén, luego cocine durante 10 a 15 minutos, o hasta que las verduras se ablanden.Regrese la carne a la sartén y revuelva los tomates y el vino. Una vez que el líquido haya sido absorbido, agregue el caldo, las hojas de laurel y un toque de salsa Worcestershire.Sazone con sal marina y pimienta negra, luego transfiera el guiso al horno para cocinar de 3 a 4 horas, o hasta que la carne esté tierna y se separe fácilmente con las horquillas.Sirva su estofado de ternera con puré de patatas cremosas y, si lo desea, un vaso de su vino tinto favorito.',
                tiempo: 240,
                precio: 200,
                estrellas: 3.8,
                video: video1,
                categoria: 'Los más comprados',
              },
              {
                id: 18,
                img: image18,
                title: 'Empanadas de carne',
                author: 'Narda Lepes',
                descripcion: 'Perfectamente condimentadas con pimentón. Rellenas de ternera tierna, son una gran opción. Rinde para 14 personas, dificultad: "no tan complicado".',
                ingredientes: 'Carne cortada a cuchillo.Papas en cubos pequeños.Cebolla de verdeo.Huevos duros.Sal, pimentón y comino',
                receta: 'Hervir las papas y retirarlas de la olla sin tirar el agua.Colocar la carne cortada a cuchillo en el agua que quedó de las papas junto con un poco de sal. El agua debe estar hirviendo, y la carne solo debe estar unos minutos para blanquearse.Poner en un recipiente las papas, la carne y los huevos duros cortados.Incorporá a este relleno la cebolla de verdeo, previamente salteada.Condimentá con el pimentón y el comino. Medite con la sal.Una vez frío, armá las empanadas como siempre.Las empanadas originales son fritas, pero te recomendamos que optes por el horno para que sean más saludables',
                tiempo: 100,
                precio: 120,
                estrellas: 3.4,
                video: video2,
                categoria: 'Los más comprados',
              },
              {
                id: 19,
                img: image19,
                title: 'Tortilla',
                author: 'Jamie Oliver',
                descripcion: 'Este plato clásico español es muy versátil y rápido de hacer. La tortilla se puede servir caliente o fría y es una forma fantástica de usar todo tipo de ingredientes: simplemente agregue los vegetales sobrantes, el queso desmenuzado o rallado, los pimientos rojos enharinados o la salchicha cocida. Para 6 porciones, dificultad: "no tan complicado".',
                ingredientes: '300 g de papas.1 cebolla.aceite de oliva.5 huevos grandes de gallinas camperas',
                receta: 'Pele las papas con un pelador rápido, luego córtelas cuidadosamente en rodajas finas. Pat las rodajas de papa secas con una toalla de té limpia.Pelar y cortar finamente la cebolla. Rocíe 2 cucharadas de aceite en una sartén pequeña a fuego medio, luego agregue la cebolla y las papas.Baje la temperatura a bajo y cocine de 25 a 30 minutos, o hasta que las cebollas estén doradas y las rodajas de papa estén bien cocidas. Trate de no remover demasiado o las papas se romperán, solo use una rebanada de pescado para voltearlas a la mitad.Agriete los huevos en un tazón para mezclar, sazone con una pizca de sal marina y pimienta negra, luego mezcle con un tenedor.Cuando las cebollas y las papas estén cocidas, retire la sartén del fuego e introdúzcalas cuidadosamente en los huevos. Transfiera la mezcla a la sartén y colóquela a fuego lento. Cocine por alrededor de 20 minutos, o hasta que casi no haya un huevo que gotea encima.Use una rebanada de pescado para levantar y aflojar ligeramente los lados de la tortilla. Con cuidado, voltee la sartén sobre un plato de cena y saque la tortilla, luego deslícela de nuevo en la sartén y cocine por otros 5 minutos, o hasta que esté dorada y cocida.Coloque la tortilla en una tabla de servir, luego córtela en 6 porciones y sirva caliente o fría con una simple ensalada verde.',
                tiempo: 35,
                precio: 100,
                estrellas: 3.5,
                video: video1,
                categoria: 'Los más comprados',
              },
              {
                id: 20,
                img: image20,
                title: 'Omelette',
                author: 'Donato Di Santis',
                descripcion: 'Un delicioso desayuno, almuerzo o cena en muy poco tiempo. Los omelettes son realmente fáciles de hacer y súper ricos. Para una persona, dificultad: "súper fácil".',
                ingredientes: '2 huevos grandes de gallinas camperas.1 pequeña perilla de mantequilla sin sal.1 pequeño puñado de queso cheddar rallado, (opcional).OPCIONAL: TOMATE Y ALBAHACA OMELETTE.2 o 3 ramitas de albahaca fresca.1 puñado de tomates cherry.aceite de oliva.OPCIONAL: MUSHROOM OMELETTE.2 o 3 setas de tipo campo.aceite de oliva',
                receta: 'Para una tortilla básica, agriete los huevos en un tazón con una pizca de sal marina y pimienta negra. Batir bien con un tenedor.Caliente una pequeña porción de mantequilla en una sartén pequeña a fuego lento, y una vez derretida y burbujeando, agregue los huevos y mueva la sartén para extenderlos uniformemente.Cuando la tortilla comience a cocinarse y se endurezca, pero aún tenga un poco de huevo crudo encima, espolvorea sobre el queso (si lo usas). A veces rejo el mío directamente en la tortilla.Con una espátula, deslízala por los bordes de la tortilla y dóblala por la mitad. Cuando empiece a dorarse por debajo, retire la sartén del fuego y deslice la tortilla en un plato.Para una tortilla de tomate y albahaca, recoja y desgarre aproximadamente las hojas de albahaca. Cortar los tomates por la mitad, luego agregar a una sartén caliente con un poco de mantequilla, un chorrito de aceite y una pizca de sal y pimienta. Freír y revolver durante 1 minuto, luego bajar la temperatura a medio y espolvorear sobre las hojas de albahaca. Agregue los huevos y mueva la sartén para extenderlos uniformemente. Continúa en cuanto a la tortilla básica.Para una tortilla de champiñones, un cuarto o pique los champiñones y agregue a una sartén caliente con un poco de mantequilla, un chorrito de aceite y una pizca de sal y pimienta. Freír y revolver hasta que estén dorados, luego bajar el fuego a medio. Agregue los huevos y mueva la sartén para extenderlos uniformemente. Cuando la tortilla comience a cocinarse y se endurezca, pero aún tenga un poco de huevo crudo encima, espolvorea sobre el Cheddar. Continúa en cuanto a la tortilla básica',
                tiempo: 10,
                precio: 80,
                estrellas: 3.3,
                video: video1,
                categoria: 'Los más comprados',
              },
              {
                id: 21,
                img: image21,
                title: 'Tostada anglo-francesa',
                author: 'Utilísima',
                descripcion: 'Con queso y jamón. El sándwich tostado se transforma con rellenos súper sabrosos. Para una persona, dificultad: "súper fácil".',
                ingredientes: '2 rebanadas de pan blanco, alrededor de 1cm de grosor.mantequilla sin sal.15 g de queso Comte.15 g de Westcombe o queso Cheddar artesanal.2 rebanadas de jamón asado de mayor bienestar.1/2 cucharada de vinagre de vino blanco.1 cucharada de aceite de colza.pimienta negra recién molida.sal marina.1 manzana pequeña para comer.1 puñado de hojas de ensalada mixtas, como frisse, berros',
                receta: 'Ligeramente unte mantequilla con las rebanadas de pan, luego coloque el lado con mantequilla hacia abajo en una tabla de cortar. Rebane y coloque los quesos sobre un pedazo de pan, cubra con el jamón y luego coloque el segundo pedazo de pan encima, con la mantequilla hacia arriba. Coloque en un fabricante de tostadas precalentadas, sujete la tapa hacia abajo y tueste de 4 a 5 minutos, o hasta que esté dorado y crujiente.Mientras tanto, agregue el vinagre y el aceite a un tarro de mermelada limpio con una pizca de sal y pimienta, levante la tapa y agite para combinar. Cortar la manzana en cerillas, quitar el núcleo, luego mezcle con las hojas de ensalada y el aderezo. Sirva la tostada dorada con la ensalada fresca al costado y dóblela.',
                tiempo: 20,
                precio: 100,
                estrellas: 3.4,
                video: video1,
                categoria: 'Los más comprados',
              },
              {
                id: 22,
                img: image22,
                title: 'Albóndigas',
                author: 'El dragón - Gourmet',
                descripcion: 'Estas albóndigas de carne de res y de cerdo, en una salsa de tomate y chile, son fáciles de hacer y saludables también. Rinde para 4, dificultad: "súper fácil".',
                ingredientes: '1 cebolla pequeña.1 chile rojo fresco.aceite de oliva.2 x 400 g de latas de tomates de ciruela de calidad.2 rebanadas de pan duro.250 g de carne picada magra o ternera de mayor bienestar.250 g de carne de cerdo de alto bienestar picada magra.1/2 cucharadita de nuez moscada molida.1 limón.1 yema de huevo grande de gallinas camperas.1 ramita de salvia fresca.1 ramita de romero fresco.1 gran puñado de guisantes de jardín.queso',
                receta: 'Pele y pique finamente la cebolla, luego corte y mache la guindilla en un mortero (o pique finamente, si lo prefiere).Calentar un chorrito de aceite en una sartén a fuego lento, agregar la cebolla y freír suavemente durante 10 a 15 minutos o hasta que esté suave.Vierta el fuego a medio, luego agregue el chile y los tomates. Llena a la mitad una de las latas de tomate con agua, dale un giro y voltéala en la sartén. Sazone ligeramente con sal marina y pimienta negra y cocine suavemente durante 30 minutos, luego rompa los tomates.Gire el pan (quite las cortezas, si lo desea) en un procesador de alimentos hasta que esté bien, luego lade en un tazón grande. Agregue la carne, la nuez moscada, la ralladura de limón, la yema de huevo y una buena pizca de condimento. Escoja, pique finamente y agregue la salvia y el romero, luego mezcle y aplaste juntos. Forme pequeñas bolitas, del tamaño de un chivo expiatorio.Caliente 3 cucharadas de aceite en una sartén grande a fuego medio-alto, agregue las albóndigas hasta que se doren, tenga cuidado de no romperlas.Una vez dorado, agregue las albóndigas a la salsa de tomate, revuelva cuidadosamente para cubrir, y cuece suavemente durante 45 minutos, o hasta que estén bien cocidas.Sirva cada porción esparcida con unos guisantes crudos, virutas de pecorino y mejorana picada (si se usa)',
                tiempo: 110,
                precio: 150,
                estrellas: 4.2,
                video: video1,
                categoria: 'Los más comprados',
              },
              {
                id: 23,
                img: image23,
                title: 'Muffins con chispas de chocolate',
                author: 'Osvaldo Gross',
                descripcion: 'Receta deliciosa e ideal para disfrutar con amigos y familia. Rinde 15 unidades, dificultad: "no tan complicado".',
                ingredientes: 'aceite de oliva o colza.375 g de harina común.1 cucharada de levadura en polvo.1/2 cucharadita de bicarbonato de sodio.10 cucharadas de mantequilla sin sal.200 g de azúcar.2 huevos grandes de gallinas camperas.Yogur natural de 360 ml.2 generosos puñados de chispas de chocolate.POMEGRANATE ICING.1 chorrito de jugo de granada.2 cucharadas de azúcar glas',
                receta: 'Precalentar el horno a 190ºC / gas 5. Engrasar ligeramente la (s) lata (s) de muffins con aceite.Tamice la harina, el polvo de hornear y la soda, y 1/2 cucharadita de sal marina.En un tazón grande, unte la mantequilla y el azúcar, batiendo hasta que quede esponjoso. Agregue los huevos, uno a la vez, batiendo hasta que se incorporen.Batir en la mitad de los ingredientes secos hasta que se mezcle, seguido de un tercio del yogur. Luego bate la mitad de los ingredientes secos restantes, seguido de otro tercio del yogur. Batir los ingredientes secos restantes y el yogur. No te sobrepases.Doble las chispas de chocolate. Distribuya la masa para muffins por igual entre las tazas y hornee de 25 a 30 minutos, hasta que estén doradas.Déle vuelta a una rejilla y déjelo enfriar.Para la guinda, agregue el jugo de granada al azúcar glas y mezcle para formar una pasta espesa. Cuando los panecillos se hayan enfriado, cubra con glaseado y espolvoree flores de saúco frescas, si está en temporada.',
                tiempo: 45,
                precio: 130,
                estrellas: 2.5,
                video: video1,
                categoria: 'Los más comprados',
              },
              {
                id: 24,
                img: image24,
                title: 'Filete a la plancha con arroz integral',
                author: 'Narda Lepes',
                descripcion: 'Ennegrecer los pimientos sobre una llama o debajo de la parrilla es una manera brillante de agregar deliciosos sabores ahumados y dulces en el plato. Rebanadas y arrojadas a través del bistec a la parrilla y sus jugos, y luego servidas con arroz herby, hacen que esta sea una cena brillante y llena de sabor. Además, el arroz integral contiene una gran fuente de vitaminas y minerales, incluido el selenio para una función eficiente del sistema inmunológico. Rinde por 2, dificultad: "no tan complicado".',
                ingredientes: '1 pimiento rojo.150 g de arroz basmati marrón.1/2 un manojo de perejil fresco de hoja plana (15g).3 cebollas de primavera.2 x 125 g de filete de flanco.aceite de oliva.25 g de pistachos sin cáscara.aceite de oliva virgen extra.1 limón.2 cucharadas de yogur natural sin grasa.30 g de queso feta',
                receta: 'Coloque el pimiento sobre la llama en su cocina o debajo de una parrilla caliente y cocine durante 15 minutos, o hasta que esté ennegrecido y lleno de ampollas, volteándolo ocasionalmente.Cocine el arroz en agua hirviendo con sal según las instrucciones del paquete, luego escurra. Regrese a la sartén y manténgase cubierto hasta que lo necesite.Una vez que esté carbonizado, coloque el pimiento en un recipiente, cubra y deje que hierva durante 10 minutos, luego déjelo enfriar.Escoja y pique finamente las hojas de perejil, luego recorte y corte finamente las cebolletas.Coloque el bistec en un tablero, cúbralo con film transparente, luego golpee con un rodillo hasta que tenga 1 cm de grosor.Deseche la película adhesiva, rocíe un poco de aceite de oliva, sazone bien con sal marina y pimienta negra, luego masajee la carne.Frote la piel de la pimienta, luego reduzca a la mitad, elimine el sabor y desgarre la carne en tiras, colocándola en un plato sobre la marcha.Coloque una sartén antiadherente grande a fuego alto, esparza los pistachos y la tostada hasta que estén dorados, luego pique aproximadamente. Regrese la sartén al fuego.Coloque el bistec en la sartén caliente, y cocine durante 6 minutos, o hasta que se dore, pero aún rosado en el medio, volteándolo regularmente.Revuelva el perejil y cebollas de primavera a través del arroz con 1 cucharada de aceite de oliva virgen extra y una pizca de pimienta. Rallar finamente la ralladura de limón y exprimir la mitad del jugo, luego apilar en platos.Mezcle el yogur con un chorrito de jugo de limón, luego sazone al gusto.Descanse el bistec por 3 minutos, luego corte en rodajas finas y mezcle con la pimienta. Coloca encima del arroz, mézclate sobre queso feta, espolvoréalos con pistachos y sírvelo con yogur',
                tiempo: 40,
                precio: 190,
                estrellas: 3.8,
                video: video1,
                categoria: 'Los más comprados',
              },
              {
                id: 25,
                img: image25,
                title: 'Brotes asados del Medio Oriente',
                author: 'Carlos Alberto “El Gato” Dumas',
                descripcion: 'Delicioso plato vegetariano y libre de gluten, con yogur cítrico y nueces tostadas machacadas. Para 4 personas, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 45,
                precio: 130,
                estrellas: 3.1,
                video: video1,
                categoria: 'Veggie',
              },
              {
                id: 26,
                img: image26,
                title: 'Panqueques salados con relleno de paneer y espinacas',
                author: 'Dolly Irigoyen',
                descripcion: 'Increíble plato vegetariano con hierbas frescas, guindillas y especias fragantes. Estos panqueques son una base versátil para cualquier relleno picante, una opción brillante para revivir el brunch posterior a la fiesta. Rinde para 8, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 60,
                precio: 160,
                estrellas: 3.8,
                video: video1,
                categoria: 'Veggie',
              },
              {
                id: 27,
                img: image27,
                title: 'Pimientos vegetarianos ahumados',
                author: 'Utilísima',
                descripcion: 'Vegetariano y sin gluten. Usar cacao en polvo ayuda a agregar una deliciosa profundidad de sabor, y nutricionalmente - tiene un alto contenido de cobre mineral, que necesitamos para mantener nuestra piel y cabello fuertes y saludables. Rinde para 8, dificultad: "no demasiado complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 105,
                precio: 120,
                estrellas: 3.4,
                video: video1,
                categoria: 'Veggie',
              },
              {
                id: 28,
                img: image28,
                title: 'Relleno de hongos mezclados',
                author: 'Francis Mallmann',
                descripcion: 'Delicioso plato vegano con nueces, hierbas y ajo. Pavo y champiñones hacen un buen par!. Sirve de 12 a 14 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 80,
                precio: 150,
                estrellas: 3.6,
                video: video1,
                categoria: 'Veggie',
              },
              {
                id: 29,
                img: image29,
                title: 'Tarta de salvia, puerro y champiñones',
                author: 'Francis Mallmann',
                descripcion: 'Plato vegetariano con queso Cheddar y pasteles de semillas de amapola. No se apresure a cocinar los puerros y las setas, ya que son las estrellas de este pastel: ambos necesitan una buena cantidad de aceite, un calor y tiempo medio para lograr su textura más integral y sabor intenso. Entre 6 y 8 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 80,
                precio: 140,
                estrellas: 4.2,
                video: video1,
                categoria: 'Veggie',
              },
              {
                id: 30,
                img: image30,
                title: 'Lasaña vegetariana',
                author: 'Carlos Alberto “El Gato” Dumas',
                descripcion: 'Con pesto casero y semillas crujientes, es una pasta imperdible. Con un toque de berenjena ahumada para intensificar el sabor, además de un relleno de pesto súper fresco. ¡Delicioso! Para 14 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 240,
                precio: 180,
                estrellas: 4.3,
                video: video1,
                categoria: 'Veggie',
              },
              {
                id: 31,
                img: image31,
                title: 'Black bean burgers',
                author: 'Narda Lepes',
                descripcion: 'Estas hamburguesas vegetarianas están repletas de proteínas, un nutriente que a menudo falta en una dieta vegetariana. ¡Pero por supuesto, no tenes que ser vegetariano para disfrutar esto! La mozzarella morada, las cebollas balsámicas picantes y un repollo crujiente y picante hacen de este plato un alimento básico para la noche, y podes lograrlo en menos de una hora. Para 2 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 40,
                precio: 125,
                estrellas: 3.7,
                video: video1,
                categoria: 'Veggie',
              },
              {
                id: 32,
                img: image32,
                title: 'Halloumi con verduras a la plancha',
                author: 'Utilísima',
                descripcion: 'Fabuloso plato vegetariano. Rápido y fácil de hacer. Rinde para 2, dificultad: "súper fácil".',
                ingredientes: '',
                receta: '',
                tiempo: 25,
                precio: 150,
                estrellas: 3.2,
                video: video1,
                categoria: 'Veggie',
              },
              {
                id: 33,
                img: image33,
                title: 'Salteado de verduras',
                author: 'El dragón - Gourmet',
                descripcion: 'Plato vegetariano con arroz frito con huevo. Súper rápido y lleno de verduras, esta es la solución perfecta para la cena. Además de ser una fuente de proteínas, también contienen vitaminas y minerales esenciales, incluida la vitamina D. Para 2 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 35,
                precio: 115,
                estrellas: 3.5,
                video: video1,
                categoria: 'Veggie',
              },
              {
                id: 34,
                img: image34,
                title: 'Brownies de chocolate sin gluten',
                author: 'Maru Botana',
                descripcion: 'Delicioso, sin gluten y vegano también. Los frijoles Aduki se usan en Japón para hacer una pasta cremosa llamada anko, que forman la base de estos brownies deliciosamente esponjosos. ¡Servilos calientes!. Para 9 porciones, dificultad: "súper fácil".',
                ingredientes: '',
                receta: '',
                tiempo: 80,
                precio: 120,
                estrellas: 3.9,
                video: video1,
                categoria: 'Veggie',
              },
              {
                id: 35,
                img: image35,
                title: 'Ensalada de berenjenas a la parrilla y pepino',
                author: 'Dolly Irigoyen',
                descripcion: 'Una deliciosa comida con semillas de sésamo tostadas. Vegano, sin gluten. Para 4 personas, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 60,
                precio: 135,
                estrellas: 3.3,
                video: video1,
                categoria: 'Veggie',
              },
              {
                id: 36,
                img: image36,
                title: 'Gnocchi alla Trapanese',
                author: 'Donato Di Santis',
                descripcion: '¡Imperdibles ñoquis! Las almendras cremosas toman el centro del escenario. Además de dar textura a toda la pasta, también te proporcionan proteínas y grasas insaturadas. Para 2 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 25,
                precio: 140,
                estrellas: 3.6,
                video: video1,
                categoria: 'Veggie',
              },
              {
                id: 37,
                img: image37,
                title: 'Cranachan de arándano congelado',
                author: 'Osvaldo Gross',
                descripcion: 'Un cremoso semifrío inspirado en el postre de avena escocés cranachan, y coronado con una crema Drambuie. Cumple todos los requisitos en cuanto a capas, sabor y textura. Para 12 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 60,
                precio: 160,
                estrellas: 3.8,
                video: video1,
                categoria: 'Tentaciones',
              },
              {
                id: 38,
                img: image38,
                title: 'Torta de chocolate Guinness',
                author: 'Maru Botana',
                descripcion: 'Con una mezcla embriagadora de Guinness y chocolate, esta torta es una delicia. Rico y oscuro, la amargura aterciopelada de la Guinness resalta el sabor del chocolate, por lo que tiene un sabor fuerte, mientras le da a la esponja un sabor sutil. La riqueza se equilibra con la dulzura del glaseado de crema agria, que hace que se parezca a la famosa stout irlandesa, negra con una cabeza cremosa. Para 10 porciones, dificultad: "no demasiado complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 70,
                precio: 170,
                estrellas: 4.0,
                video: video1,
                categoria: 'Tentaciones',
              },
              {
                id: 39,
                img: image39,
                title: 'Mousse de chocolate con ciruelas',
                author: 'Buddy Valastro',
                descripcion: 'Riquísimo y tentador postre vegetariano y sin gluten. Cualquier mezcla de ciruela pasa se mantendrá en un recipiente hermético hasta un mes. Rinde para 12/14 porciones, dificultad: "no tan complicado".',
                ingredientes: '350 g de chocolate negro (70%), más extra para servir.100 ml de crema doble.10 huevos.50 g de azúcar en polvo de oro.500 g de ciruelas secas.150 ml de whisky.100 ml de jugo de naranja sin azúcar fresco',
                receta: 'Prepara las ciruelas la noche anterior: combina las ciruelas pasas, el whisky y el jugo de naranja en un tazón y déjalo en remojo toda la noche. Al día siguiente, divida el chocolate y derrita en un recipiente colocado sobre una fuente de agua hirviendo, asegurándose de que el recipiente no toque el agua. Retire el recipiente del fuego y déjelo enfriar.',
                tiempo: 150,
                precio: 165,
                estrellas: 3.7,
                video: video1,
                categoria: 'Tentaciones',
              },
              {
                id: 40,
                img: image40,
                title: 'Blackcurrant ombré cheesecake',
                author: 'Buddy Valastro',
                descripcion: 'Este cheesecake con base de galleta de avena y cobertura de gelatina de bayas sabe tan bien como parece. El efecto ombré es una gran pieza central: ¡tus amigos nunca adivinarán lo fácil que es hacer! Para 12 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 45,
                precio: 120,
                estrellas: 3.5,
                video: video1,
                categoria: 'Tentaciones',
              },
              {
                id: 41,
                img: image41,
                title: 'Helado de banana y canela',
                author: 'Utilísima',
                descripcion: 'Increíble helado vegetariano y sin gluten. Postre fácil de hacer y tan difícil de resistir. Para 8 porciones, dificultad: "súper fácil".',
                ingredientes: '',
                receta: '',
                tiempo: 30,
                precio: 100,
                estrellas: 3.2,
                video: video1,
                categoria: 'Tentaciones',
              },
              {
                id: 42,
                img: image42,
                title: 'Torta de chocolate',
                author: 'Jamie Oliver',
                descripcion: 'Torta sin gluten súper rápida de hacer. El polen de abeja proporciona el intenso estallido de sabores a miel y su crujido satisfactorio. Para 16 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 25,
                precio: 130,
                estrellas: 3.7,
                video: video1,
                categoria: 'Tentaciones',
              },
              {
                id: 43,
                img: image43,
                title: 'Torta de calabaza con nueces pecanas',
                author: 'Jamie Oliver',
                descripcion: 'Con un topping crujiente de nueces pegajoso y dulce, ¡es un verdadero placer! Proporciona una dulzura natural. Para 12 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 170,
                precio: 160,
                estrellas: 3.5,
                video: video1,
                categoria: 'Tentaciones',
              },
              {
                id: 44,
                img: image44,
                title: 'Squaffee pie',
                author: 'Utilísima',
                descripcion: 'Fabuloso postre vegetariano con una llovizna de caramelo de café. Posee un relleno denso y rico, perfecto para capas con caramelo. Para 12 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 90,
                precio: 145,
                estrellas: 3.4,
                video: video1,
                categoria: 'Tentaciones',
              },
              {
                id: 45,
                img: image45,
                title: 'Tarta de manzana',
                author: 'Maru Botana',
                descripcion: 'Esta versión es ligeramente especiada y absolutamente deliciosa ahogada en natillas. Para 6 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 90,
                precio: 120,
                estrellas: 3.2,
                video: video1,
                categoria: 'Tentaciones',
              },
              {
                id: 46,
                img: image46,
                title: 'Hot cross muffins',
                author: 'Utilísima',
                descripcion: 'Un regalo de Pascuas sin gluten. Para 24 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 80,
                precio: 110,
                estrellas: 3.3,
                video: video1,
                categoria: 'Tentaciones',
              },
              {
                id: 47,
                img: image47,
                title: 'Deliciosa mousse de chocolate',
                author: 'Buddy Valastro',
                descripcion: 'Riquisimo postre sin gluten, con guindas y chapas de sésamo molidas. Esta receta de mousse de chocolate está repleta de ingredientes deliciosos y un poco traviesos. Para 10 porciones, dificultad: "súper fácil".',
                ingredientes: '',
                receta: '',
                tiempo: 30,
                precio: 135,
                estrellas: 4.4,
                video: video1,
                categoria: 'Tentaciones',
              },
              {
                id: 48,
                img: image48,
                title: 'Tarta de rizo de limón',
                author: 'Utilísima',
                descripcion: 'Deliciosa tarta vegetariana. Con sólo un bocado obtendrá un suave relleno de limón, una masa quebradiza y un poco de azúcar caramelizado. Para 10 porciones, dificultad: "para presumir".',
                ingredientes: '',
                receta: '',
                tiempo: 60,
                precio: 120,
                estrellas: 3.5,
                video: video1,
                categoria: 'Tentaciones',
              },
              {
                id: 49,
                img: image49,
                title: 'Empanadas de queso',
                author: 'Narda Lepes',
                descripcion: 'Excelente opción para sorprender a tus invitados. Rellenas del mejor queso, sabor único. Rinde para 14 personas, dificultad: "no tan complicado"',
                ingredientes: '15 tapas medianas para empanadas de horno o 25 tapas pequeñas.3 tazas de queso desmenuzado o rallado.Media cebolla blanca, picada finamente. 1 huevo, la yema y la clara separadas, batidas ligeramente.2-3 cucharadas de azúcar demerara (tipo de azúcar que mantiene su forma cristalizada al horno)',
                receta: 'Mezcle el queso y la cebolla picada.Para formar las empanadas ponga una cucharada de la mezcla del queso y cebolla en el centro de las tapas de empanadas.Usando una brocha pastelera rocíe los bordes de las tapas con la clara de huevo (esto ayudara a sellar las empanadas para prevenir que el queso se derrame cuando se estén horneando).Doble las tapas y selle los bordes usando un tenedor.Pinte la parte superior de las empanadas con la yema de huevo, esto les dará un bonito color dorado cuando se horneen.Espolvoree la azúcar en la parte superior de las empanadas.Refrigere las empanadas por los menos durante una media hora, esto ayudara a que se sellen correctamente.Pre-caliente el horno a 400 F y hornee las empanadas durante 20-25 minutos o hasta que se empiecen a dorar.Sirva las empanadas calientes',                
                tiempo: 100,
                precio: 180,
                estrellas: 4.5,
                video: video1,
                categoria: 'Recomendados',
              },
              {
                id: 50,
                img: image50,
                title: 'Paella',
                author: 'Narda Lepes',
                descripcion: 'Hay mil formas de preparar una paella ya que admite prácticamente cualquier ingrediente que le quieras añadir. Su elaboración requiere de cierta práctica para respetar los tiempos de cocción y no sobre-cocer la paella, dando lugar al temido arroz pasado, pero con nuestras recetas y consejos, te garantizamos que ese sabor está garantizado',                
                ingredientes: '15 tapas medianas para empanadas de horno o 25 tapas pequeñas.3 tazas de queso desmenuzado o rallado (use mozzarella si no puede conseguir un buen queso fresco).Media cebolla blanca, picada finamente. 1 huevo, la yema y la clara separadas, batidas ligeramente.2-3 cucharadas de azúcar demerara (tipo de azúcar que mantiene su forma cristalizada al horno)',
                receta: 'Empezamos haciendo el sofrito. Para ello, freímos la cebolla bien picada en el aceite caliente. Removemos la cebolla con una cuchara de madera frecuentemente, para que no se queme, y lo dejamos hasta que comience a tomar color.En ese momento, añadimos el ajo bien picado y, antes de que empiece a tomar color, incorporamos los tomates también picados.Agregamos el azúcar (para neutralizar la acidez del tomate), sal a nuestro gusto, el pimentón y unas hebras de azafrán. Revolvemos todos los ingredientes y dejamos que se sofrían hasta que los tomates se reduzcan y comiencen a chisporrotear.Es el momento de cortar los calamares ya limpios. El cuerpo lo cortamos en aros y las patas las dejamos enteras. Añadimos el calamar y lo dejamos cocinar durante unos minutos.Incorporamos el arroz y lo distribuimos por toda la paellera para que los granos se adhieran a los ingredientes. Calentamos el caldo junto con el vino en un cazo aparte, y cuando esté caliente lo vertemos en la paella.Aumentamos la temperatura y añadimos más sal. Volvemos a remover todo para que el arroz quede bien cubierto por el caldo, y cuando llegue a ebullición, bajamos la temperatura y dejamos que se cueza todo a fuego lento de 18 a 20 minutos.Es importante que durante la cocción vayamos moviendo la paellera por toda la superficie de cocción, para que el arroz se cueza uniformemente.Tras 10 minutos de cocción, incorporamos las gambas cocidas por encima hasta que se pongan de color rosa, luego le damos la vuelta para que se hagan por el otro lado.',
                precio: 120,
                estrellas: 3.4,
                video: video1,
                categoria: 'Recomendados',
              },
              {
                id: 51,
                img: image51,
                title: 'Guacamole',
                author: 'Narda Lepes',
                descripcion: 'Hay mil formas de preparar una paella ya que admite prácticamente cualquier ingrediente que le quieras añadir. Su elaboración requiere de cierta práctica para respetar los tiempos de cocción y no sobre-cocer la paella, dando lugar al temido arroz pasado, pero con nuestras recetas y consejos, te garantizamos que ese sabor está garantizado',                
                ingredientes: '3 aguacates maduros medianos.1 cebolla mediana (si puede ser, dulce).El zumo de una lima recién exprimida.Un pimiento jalapeño.Un chile serrano.Cilantro fresco recién picado.Un poco de sal (a discreción)',
                receta: 'Quitar el hueso del aguacate y le sacarlr la pulpa con una cuchara.Machacar la pulpa con un tenedor hasta dejarla com una masa cremosa, pero con cierta consistencia, como si se tratase de un puré.Agregar el zumo de lima recién exprimida para evitar que el aguacate se oxide y adquiera un color oscuro.Pelar la cebolla y picar la mitad en trozos muy finos, algo que podemos hacer o con un cuchillo muy afilado o con una mandolina. Incorporar la cebolla al aguacate que tenemos en el plato ya triturado.Picar el jalapeño muy fino, procurando quitarle las pepitas si no queremos que pique demasiado, lo incorporaremos al resto de ingredientes junto a un pellizco de sal y a unas hojas de cilantro fresco recién picado.Con el tenedor remover todos los ingredientes para que poco a poco se vayan mezclando todos los ingredientes y encontrando el equilibrio entre todos ellos.Ahora ya estará listo para consumir con cualquiera de las elaboraciones de la gastronomía mexicana que hayamos hecho, desde unos sencillos nachos hasta un plato de pollo o carne picante.',
                precio: 100,
                estrellas: 4.2,
                video: video1,
                categoria: 'LosMasComprados',
              }
            ],
  };

export default appData;