import image1 from './img/Recomendados/1.jpg';
import image2 from './img/Recomendados/2.jpg';
import image3 from './img/Recomendados/3.jpg';
import image4 from './img/Recomendados/4.jpg';
import image5 from './img/Recomendados/5.jpg';
import image6 from './img/Recomendados/6.jpg';
import image7 from './img/Recomendados/7.jpg';
import image8 from './img/Recomendados/8.jpg';
import image9 from './img/Recomendados/9.jpg';
import image10 from './img/Recomendados/10.jpg';
import image11 from './img/Recomendados/11.jpg';
import image12 from './img/Recomendados/12.jpg';
import image13 from './img/LosMasComprados/2.jpg';
import image14 from './img/LosMasComprados/3.jpg';
import image15 from './img/LosMasComprados/4.jpg';
import image16 from './img/LosMasComprados/5.jpg';
import image17 from './img/LosMasComprados/1.jpg';
import image18 from './img/LosMasComprados/6.jpg';
import image19 from './img/LosMasComprados/7.jpg';
import image20 from './img/LosMasComprados/8.jpg';
import image21 from './img/LosMasComprados/9.jpg';
import image22 from './img/LosMasComprados/10.jpg';
import image23 from './img/LosMasComprados/11.jpg';
import image24 from './img/LosMasComprados/12.jpg';
import image25 from './img/Veggie/1.jpg';
import image26 from './img/Veggie/2.jpg';
import image27 from './img/Veggie/3.jpg';
import image28 from './img/Veggie/4.jpg';
import image29 from './img/Veggie/5.jpg';
import image30 from './img/Veggie/6.jpg';
import image31 from './img/Veggie/7.jpg';
import image32 from './img/Veggie/8.jpg';
import image33 from './img/Veggie/9.jpg';
import image34 from './img/Veggie/10.jpg';
import image35 from './img/Veggie/11.jpg';
import image36 from './img/Veggie/12.jpg';
import image37 from './img/Tentaciones/1.jpg';
import image38 from './img/Tentaciones/2.jpg';
import image39 from './img/Tentaciones/3.jpg';
import image40 from './img/Tentaciones/4.jpg';
import image41 from './img/Tentaciones/5.jpg';
import image42 from './img/Tentaciones/6.jpg';
import image43 from './img/Tentaciones/7.jpg';
import image44 from './img/Tentaciones/8.jpg';
import image45 from './img/Tentaciones/9.jpg';
import image46 from './img/Tentaciones/10.jpg';
import image47 from './img/Tentaciones/11.jpg';
import image48 from './img/Tentaciones/12.jpg';
import video1 from './img/Videos/nardalepes.jpg';

  const appData = {
    // Por ahora hay un solo usuario super hardcodeado
    // con sus datos, favoritos, platos comprados y packs comprados.
    usuario: {
              username: 'Pepenacho',
              nombre: 'José',
              apellido: 'Sbruzzi',
              direccion: 'Paseo Colón 850',
              tarjetaNumero: 'XXXX-XXXX-XXXX-8745',
    },
    favoritos: [9,16,19,29,34],
    comprados: [4,6,39],
    packsComprados: [2],
    carrito: [
              {
                idPlato: 5,
                cantidad: 2,
              },
              {
                idPlato: 2,
                cantidad: 1,
              }
            ],
    packs: [
            {
              id: 1,
              platos: [2,3],
            },
            {
              id: 2,
              platos: [1,4],
            },
            {
              id: 3,
              platos: [5,6,3],
            }
           ],
    platos: [
              {
                id: 1,
                img: image1,
                title: 'Canelones al horno',
                author: 'Carlos Alberto “El Gato” Dumas',
                descripcion: 'Nada mejor que disfrutar de una excelente pasta con espinaca, nueces y salvia crujiente. Con su delicioso relleno de tres quesos, este canelón de vegetales dorados es un verdadero placer. Para 8 porciones, dificultad: "súper fácil".',
                ingredientes: '',
                receta: '',
                tiempo: 40,
                precio: 150,
                estrellas: 4.3,
                video: video1,
                categoria: 'Recomendados',
              },
              {
                id: 2,
                img: image2,
                title: 'Pechuga de pollo asada con tomates cherry y espárragos',
                author: 'Enrique Gonzales',
                descripcion: 'No espere más a que venga la familia para disfrutar de un asado. Esta mini versión es genial cualquier día de la semana. Para una persona, dificultad: "súper fácil".',
                ingredientes: '',
                receta: '',
                tiempo: 40,
                precio: 170,
                estrellas: 3.5,
                video: video1,               
                categoria: 'Recomendados',
              },
              {
                id: 3,
                img: image3,
                title: 'Pasta al pesto',
                author: 'Utilísima',
                descripcion: 'Fideos deliciosos, con ajo y pollo al romeo. A todo el mundo le gusta la pasta al pesto. Agregar el pollo y las judías verdes hace que la cena se vuelva espectacular. Para 4 porciones, dificultad: "súper fácil".',
                ingredientes: '',
                receta: '',
                tiempo: 15,
                precio: 100,
                estrellas: 4.0,
                video: video1,                
                categoria: 'Recomendados',
              },
              {
                id: 4,
                img: image4,
                title: 'Bruschetta de Gennaro',
                author: 'El dragón - Gourmet',
                descripcion: 'Plato delicioso con verduras asadas. Esta bruschetta también va muy bien con carne y pescado. Para una persona, dificultad: "súper fácil".',
                ingredientes: '1 rebanada de pan de masa fermentada.1 pedazo de nabo asado.2 piezas de remolacha asada.1 pieza de pastinaca asada.sal marina.pimienta negra recién molida.aceite de oliva virgen extra.vinagre balsámico.1 diente de ajo, sin pelar y reducido a la mitad.2 ramitas de perejil fresco de hoja plana.1 puñado de hojas de ensalada mixta, lavadas e hiladas en seco.1 ramita de menta.fresca, hojas recogidas.1 limón.queso parmesano',
                receta: 'Siempre y cuando tenga un poco de ajo crudo para frotar sobre el pan tostado y un buen aceite de oliva, puede hacer bruschetta. Cualquier cosa que pongas encima después de eso, de carne sobrante, mariscos o incluso anchoas simples, será delicioso. Uno de mis combos favoritos es el cordero sobrante, menta fresca y un chorrito de vinagre de jerez ... ¡vamos!.Estos bruschetta de vegetales tostados son deliciosos y fáciles. Todo lo que tiene que hacer es sazonar y vestir los vegetales tostados sobrantes con cuidado para que vuelvan a la vida y tenga un refrigerio perfecto o un almuerzo ligero.Coloque el pan en una sartén caliente y tápelo en ambos lados. Mientras esto sucede, use la parte posterior de un tenedor o cuchillo para mezclar aproximadamente las verduras en una tabla de madera. Sazone con sal y pimienta, rocíe un poco de aceite de oliva virgen extra y un poco de balsámico, luego revuelva. Una vez que el pan tenga marcas agradables de carbonilla en ambos lados, frote el diente de ajo cortado sobre el sabor y luego ponga las verduras en puré encima. Picar finamente el perejil y esparcirlo encima.Mezcle la ensalada y las hojas de menta en un bol con una buena pizca de sal, un chorrito de aceite de oliva virgen extra, un chorrito de balsámico y un chorrito de jugo de limón. Coloque una pizca de hojas de ensalada encima de la bruschetta y luego raspe con un parmesano. Termine con un chorrito de aceite de oliva virgen extra y sirva inmediatamente con el resto de la ensalada en el lateral',
                tiempo: 15,
                precio: 175,
                estrellas: 3.6,
                video: video1,               
                categoria: 'Recomendados',
              },
              {
                id: 5,
                img: image5,
                title: 'Alitas de pollo: estilo agridulce',
                author: 'Jamie Oliver',
                descripcion: 'Alitas de pollo dulces y deliciosas con espléndido glaseado de miel. Este es un plato muy simple que invierte en grandes sabores, por lo que sólo necesita una bruschetta a la parrilla y cebollas cortadas en vinagre para servir. Rinde entre 4/6, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 75,
                precio: 150,
                estrellas: 3.7,
                video: video1,                
                categoria: 'Recomendados',
              },
              {
                id: 6,
                img: image6,
                title: 'Ensalada César de pollo asado',
                author: 'Narda Lepes',
                descripcion: 'Lleve su ensalada de pollo César a la próxima galaxia poniendo el pollo en salmuera durante la noche, lo que agregará un montón de sabor, jugosidad y caramelización, y asando sus crotones en los jugos del pollo para la textura y sabor final. Rinde entre 10 y 12, dificultad: "para presumir".',
                ingredientes: '2,5 kg de pollo entero de corral.400 g de pan de masa fermentada.aceite de oliva.1 diente de ajo.50 g de estaño de anchoas en aceite, de fuentes sostenibles.1 manojo de perejil fresco de hoja plana, (30g). 2 chiles rojos frescos. aceite de oliva virgen extra. 1 limón. 4 lechugas romanas. 150 g de rábanos de color mezclado. 1 pepino. ½ un montón de cebolletas frescas, (15g). SALMUERA. 4 cucharadas de pimienta negra. 4 cucharadas de semillas de hinojo. 2 litros de jugo de manzana fresca. 100 g de sal marina. ½ un manojo de tomillo fresco, (15g). 12 hojas frescas de laurel. 6 chiles rojos secos. ADEREZO CÉSAR. 50 g de queso parmesano, más extra para servir. 1 cucharadita de mostaza inglesa. 2 cucharaditas de salsa Worcestershire. 250 g de yogur griego. 1 limón',
                receta: 'Para la salmuera, tuesta los granos de pimienta y las semillas de hinojo en una olla grande a fuego alto durante 1 minuto, luego agregue el jugo de manzana, sal marina, tomillo y la bahía.Revuelva en los chiles secos y deje que hierva, luego retírelo del fuego, rellene con 1 litro de agua fría y luego deje que se enfríe completamente.Use un cuchillo afilado para cortar con cuidado la parte posterior del pollo para que pueda abrirlo y luego agregarlo a la salmuera enfriada (transfiéralo a un recipiente más grande, si es necesario).Cubra con film transparente y déjelo en la nevera durante al menos 12 horas, luego drene y seque con papel de cocina.Precalentar el horno a 200ºC / 400ºF / gas 6.Rompa la masa madre en trozos grandes y déjela a un lado. Frote 1 cucharada de aceite de oliva por todo el pollo y colóquelo directamente sobre las barras del horno, con la piel hacia arriba, y coloque una bandeja grande exactamente debajo para atrapar los jugos deliciosos.Tueste por 30 minutos, luego baje el horno a 160ºC / 325ºF / gas 3. Agregue la masa madre a los jugos en la bandeja, luego rompa el bulbo de ajo y esparza los dientes sin pelar, luego mezcle todo para cubrir.Asar durante 1 hora, o hasta que el pollo esté dorado y bien cocido, tirando ocasionalmente los crutones de masa fermentada para cocinar uniformemente. Deje que el pollo descanse durante 30 minutos antes de tallar.Escurra las anchoas (guardando el aceite) y corta por la mitad a lo largo, luego coloca el plato en forma cruzada.Pica finamente los tallos de perejil, reservando las hojas para después. Cortar finamente la guindilla y esparcir sobre las anchoas, junto con los tallos de perejil. Rocíe con ½ cucharada sopera de cada aceite de oliva de anchoa y aceite de oliva virgen extra, luego ralle finamente la mitad de la ralladura de limón y exprima la mitad del jugo. Déjalo marinar. Para el aderezo César, ralla finamente el parmesano en un bol, agrega la mostaza, la salsa Worcestershire y el yogur, luego bate para combinar.Exprima el jugo de limón, vierta 8 cucharadas de aceite de oliva virgen extra y vuelva a mezclar. Pruebe y sazone a la perfección, aflojando con un chorrito de agua, si es necesario.Corta las lechugas y los rábanos y raspa un tenedor por los lados del pepino. Cortar finamente los rábanos, el pepino, las hojas de perejil y el cebollín, cortar la lechuga aproximadamente y colocar todo en un tazón grande.Coloque el pollo y la mitad de los crotones de ajo en una tabla. Agregue los crotones restantes al tazón de ensalada, vierta más de la mitad del aderezo y mezcle todo.Afeitarse un poco de parmesano con un pelador de velocidad, luego llevar a la mesa con las anchoas marinadas, pollo, crutones extra y aderezo. Deje que todos caven y construyan su propia ensalada César.',
                tiempo: 105,
                precio: 130,
                estrellas: 3.3,
                video: video1,                
                categoria: 'Recomendados',
              },
              {
                id: 7,
                img: image7,
                title: 'Pan de queso y ajo',
                author: 'Osvaldo Gross',
                descripcion: 'Receta para lograr un pan de queso y ajo riquísimo. Rinde entre 4 y 6 personas, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 110,
                precio: 120,
                estrellas: 4.2,
                video: video1,                
                categoria: 'Recomendados',
              },
              {
                id: 8,
                img: image8,
                title: 'Tacos de pescado mexicano',
                author: 'Enrique Olvera',
                descripcion: 'Increíbles tacos de pescado con todos los adornos: guacamole grueso, salsa de piña dulce, crema agria de ajo y un repollo con jalapeño. Sirve a 4, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 85,
                precio: 160,
                estrellas: 3.9,
                video: video1,               
                categoria: 'Recomendados',
              },
              {
                id: 9,
                img: image9,
                title: 'Tarta primavera',
                author: 'Mauro Colagreco',
                descripcion: 'Tocino rayado, espinacas y puerros en masa filo. Ideal para prepararlo junto a los chicos ya que es un plato muy desordenado y en donde "se tira todo". Sirve a 6, dificultad: "súper fácil".',
                ingredientes: '',
                receta: '',
                tiempo: 55,
                precio: 180,
                estrellas: 4.0,
                video: video1,               
                categoria: 'Recomendados',
              },
              {
                id: 10,
                img: image10,
                title: 'Sushi de espárragos',
                author: 'El dragón - Gourmet',
                descripcion: 'Ingredientes preparados para que puedas cocinar sushi. Delicioso sushi con aguacate y salsa de lima. Para 24 piezas, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 45,
                precio: 200,
                estrellas: 3.7,
                video: video1,
                categoria: 'Recomendados',
              },
              {
                id: 11,
                img: image11,
                title: 'Pollo y papas fritas mediterráneas',
                author: 'Utilísima',
                descripcion: 'Preciosas patas de pollo con limón y papas nuevas trituradas, todo cocinado en una bandeja: es una cena sencilla y satisfactoria, y los sabores herbales traerán un poco de sol a la mesa. Para 4 personas, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 60,
                precio: 200,
                estrellas: 3.2,
                video: video1,
                categoria: 'Recomendados',
              },
              {
                id: 12,
                img: image12,
                title: 'Ensalada de sushi simple',
                author: 'El dragón - Gourmet',
                descripcion: 'Con salmón ahumado, aguacate y col rizada. Rinde para 2 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 35,
                precio: 130,
                estrellas: 3.5,
                video: video1,
                categoria: 'Recomendados',
              },
              {
                id: 13,
                img: image13,
                title: 'Insanity burger',
                author: 'Jamie Oliver',
                descripcion: 'Con mostaza y salsa de hamburguesa casera, utiliza la técnica de cepillar las hamburguesas con mostaza y un chorrito de salsa Chipotle de Tabasco mientras se cocinan para formar una increíble capa de condimento. Rinde para 4, dificultad: "súper fácil".',
                ingredientes: '',
                receta: '',
                tiempo: 35,
                precio: 120,
                estrellas: 3.5,
                video: video1,
                categoria: 'Los más comprados',
              },
              {
                id: 14,
                img: image14,
                title: 'Las papas perfectas',
                author: 'Maru Botana',
                descripcion: 'Las papas fritas o patatas fritas, también conocidas como papas a la francesa o patatas a la francesa, son las papas que se preparan cortándose en rodajas o en forma de bastones y friéndolas en aceite caliente hasta que queden doradas, retirándolas del aceite y luego sazonándolas con sal. Para 4 personas, dificultad: "no tan complicado"',
                ingredientes: '',
                receta: '',
                tiempo: 40,
                precio: 110,
                estrellas: 4.3,
                video: video1,
                categoria: 'Los más comprados',
              },
              {
                id: 15,
                img: image15,
                title: 'Pizza básica',
                author: 'Donato De Santis',
                descripcion: 'Deliciosa masa y cobertura. Una vez que vean lo simple y sabrosa que es esta receta de masa de pizza, no querrán comida para llevar. Sirve 8 porciones, dificultad: "súper fácil".',
                ingredientes: '',
                receta: '',
                tiempo: 80,
                precio: 200,
                estrellas: 4.3,
                video: video1,
                categoria: 'Los más comprados',
              },
              {
                id: 16,
                img: image16,
                title: 'Chocotorta',
                author: 'Maru Botana',
                descripcion: 'Delicioso postre, simple y rápido de hacer. Se logra utilizando chocolinas y una mezcla de dulce de leche y queso crema. Para compartir... o no, dificultad "súper fácil".',
                ingredientes: '',
                receta: '',
                tiempo: 30,
                precio: 130,
                estrellas: 4.2,
                video: video1,
                categoria: 'Los más comprados',
              },
              {
                id: 17,
                img: image17,
                title: 'Estofado de carne',
                author: 'Utilísima',
                descripcion: 'Una receta de estofado de ternera tierna con una preparación mínima: ponerla en el horno enseguida y dejarla actuar de manera mágica. Para 6 personas, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 240,
                precio: 200,
                estrellas: 3.8,
                video: video1,
                categoria: 'Los más comprados',
              },
              {
                id: 18,
                img: image18,
                title: 'Empanadas de carne',
                author: 'Narda Lepes',
                descripcion: 'Perfectamente condimentadas con pimentón. Rellenas de ternera tierna, son una gran opción. Rinde para 14 personas, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 100,
                precio: 120,
                estrellas: 3.4,
                video: video1,
                categoria: 'Los más comprados',
              },
              {
                id: 19,
                img: image19,
                title: 'Tortilla',
                author: 'Jamie Oliver',
                descripcion: 'Este plato clásico español es muy versátil y rápido de hacer. La tortilla se puede servir caliente o fría y es una forma fantástica de usar todo tipo de ingredientes: simplemente agregue los vegetales sobrantes, el queso desmenuzado o rallado, los pimientos rojos enharinados o la salchicha cocida. Para 6 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 35,
                precio: 100,
                estrellas: 3.5,
                video: video1,
                categoria: 'Los más comprados',
              },
              {
                id: 20,
                img: image20,
                title: 'Omelette',
                author: 'Donato Di Santis',
                descripcion: 'Un delicioso desayuno, almuerzo o cena en muy poco tiempo. Los omelettes son realmente fáciles de hacer y súper ricos. Para una persona, dificultad: "súper fácil".',
                ingredientes: '',
                receta: '',
                tiempo: 10,
                precio: 80,
                estrellas: 3.3,
                video: video1,
                categoria: 'Los más comprados',
              },
              {
                id: 21,
                img: image21,
                title: 'Tostada anglo-francesa',
                author: 'Utilísima',
                descripcion: 'Con queso y jamón. El sándwich tostado se transforma con rellenos súper sabrosos. Para una persona, dificultad: "súper fácil".',
                ingredientes: '',
                receta: '',
                tiempo: 20,
                precio: 100,
                estrellas: 3.4,
                video: video1,
                categoria: 'Los más comprados',
              },
              {
                id: 22,
                img: image22,
                title: 'Albóndigas',
                author: 'El dragón - Gourmet',
                descripcion: 'Estas albóndigas de carne de res y de cerdo, en una salsa de tomate y chile, son fáciles de hacer y saludables también. Rinde para 4, dificultad: "súper fácil".',
                ingredientes: '',
                receta: '',
                tiempo: 110,
                precio: 150,
                estrellas: 4.2,
                video: video1,
                categoria: 'Los más comprados',
              },
              {
                id: 23,
                img: image23,
                title: 'Muffins con chispas de chocolate',
                author: 'Osvaldo Gross',
                descripcion: 'Receta deliciosa e ideal para disfrutar con amigos y familia. Rinde 15 unidades, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 45,
                precio: 130,
                estrellas: 2.5,
                video: video1,
                categoria: 'Los más comprados',
              },
              {
                id: 24,
                img: image24,
                title: 'Filete a la plancha con arroz integral',
                author: 'Narda Lepes',
                descripcion: 'Ennegrecer los pimientos sobre una llama o debajo de la parrilla es una manera brillante de agregar deliciosos sabores ahumados y dulces en el plato. Rebanadas y arrojadas a través del bistec a la parrilla y sus jugos, y luego servidas con arroz herby, hacen que esta sea una cena brillante y llena de sabor. Además, el arroz integral contiene una gran fuente de vitaminas y minerales, incluido el selenio para una función eficiente del sistema inmunológico. Rinde por 2, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 40,
                precio: 190,
                estrellas: 3.8,
                video: video1,
                categoria: 'Los más comprados',
              },
              {
                id: 25,
                img: image25,
                title: 'Brotes asados del Medio Oriente',
                author: 'Carlos Alberto “El Gato” Dumas',
                descripcion: 'Delicioso plato vegetariano y libre de gluten, con yogur cítrico y nueces tostadas machacadas. Para 4 personas, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 45,
                precio: 130,
                estrellas: 3.1,
                video: video1,
                categoria: 'Veggie',
              },
              {
                id: 26,
                img: image26,
                title: 'Panqueques salados con relleno de paneer y espinacas',
                author: 'Dolly Irigoyen',
                descripcion: 'Increíble plato vegetariano con hierbas frescas, guindillas y especias fragantes. Estos panqueques son una base versátil para cualquier relleno picante, una opción brillante para revivir el brunch posterior a la fiesta. Rinde para 8, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 60,
                precio: 160,
                estrellas: 3.8,
                video: video1,
                categoria: 'Veggie',
              },
              {
                id: 27,
                img: image27,
                title: 'Pimientos vegetarianos ahumados',
                author: 'Utilísima',
                descripcion: 'Vegetariano y sin gluten. Usar cacao en polvo ayuda a agregar una deliciosa profundidad de sabor, y nutricionalmente - tiene un alto contenido de cobre mineral, que necesitamos para mantener nuestra piel y cabello fuertes y saludables. Rinde para 8, dificultad: "no demasiado complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 105,
                precio: 120,
                estrellas: 3.4,
                video: video1,
                categoria: 'Veggie',
              },
              {
                id: 28,
                img: image28,
                title: 'Relleno de hongos mezclados',
                author: 'Francis Mallmann',
                descripcion: 'Delicioso plato vegano con nueces, hierbas y ajo. Pavo y champiñones hacen un buen par!. Sirve de 12 a 14 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 80,
                precio: 150,
                estrellas: 3.6,
                video: video1,
                categoria: 'Veggie',
              },
              {
                id: 29,
                img: image29,
                title: 'Tarta de salvia, puerro y champiñones',
                author: 'Francis Mallmann',
                descripcion: 'Plato vegetariano con queso Cheddar y pasteles de semillas de amapola. No se apresure a cocinar los puerros y las setas, ya que son las estrellas de este pastel: ambos necesitan una buena cantidad de aceite, un calor y tiempo medio para lograr su textura más integral y sabor intenso. Entre 6 y 8 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 80,
                precio: 140,
                estrellas: 4.2,
                video: video1,
                categoria: 'Veggie',
              },
              {
                id: 30,
                img: image30,
                title: 'Lasaña vegetariana',
                author: 'Carlos Alberto “El Gato” Dumas',
                descripcion: 'Con pesto casero y semillas crujientes, es una pasta imperdible. Con un toque de berenjena ahumada para intensificar el sabor, además de un relleno de pesto súper fresco. ¡Delicioso! Para 14 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 240,
                precio: 180,
                estrellas: 4.3,
                video: video1,
                categoria: 'Veggie',
              },
              {
                id: 31,
                img: image31,
                title: 'Black bean burgers',
                author: 'Narda Lepes',
                descripcion: 'Estas hamburguesas vegetarianas están repletas de proteínas, un nutriente que a menudo falta en una dieta vegetariana. ¡Pero por supuesto, no tenes que ser vegetariano para disfrutar esto! La mozzarella morada, las cebollas balsámicas picantes y un repollo crujiente y picante hacen de este plato un alimento básico para la noche, y podes lograrlo en menos de una hora. Para 2 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 40,
                precio: 125,
                estrellas: 3.7,
                video: video1,
                categoria: 'Veggie',
              },
              {
                id: 32,
                img: image32,
                title: 'Halloumi con verduras a la plancha',
                author: 'Utilísima',
                descripcion: 'Fabuloso plato vegetariano. Rápido y fácil de hacer. Rinde para 2, dificultad: "súper fácil".',
                ingredientes: '',
                receta: '',
                tiempo: 25,
                precio: 150,
                estrellas: 3.2,
                video: video1,
                categoria: 'Veggie',
              },
              {
                id: 33,
                img: image33,
                title: 'Salteado de verduras',
                author: 'El dragón - Gourmet',
                descripcion: 'Plato vegetariano con arroz frito con huevo. Súper rápido y lleno de verduras, esta es la solución perfecta para la cena. Además de ser una fuente de proteínas, también contienen vitaminas y minerales esenciales, incluida la vitamina D. Para 2 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 35,
                precio: 115,
                estrellas: 3.5,
                video: video1,
                categoria: 'Veggie',
              },
              {
                id: 34,
                img: image34,
                title: 'Brownies de chocolate sin gluten',
                author: 'Maru Botana',
                descripcion: 'Delicioso, sin gluten y vegano también. Los frijoles Aduki se usan en Japón para hacer una pasta cremosa llamada anko, que forman la base de estos brownies deliciosamente esponjosos. ¡Servilos calientes!. Para 9 porciones, dificultad: "súper fácil".',
                ingredientes: '',
                receta: '',
                tiempo: 80,
                precio: 120,
                estrellas: 3.9,
                video: video1,
                categoria: 'Veggie',
              },
              {
                id: 35,
                img: image35,
                title: 'Ensalada de berenjenas a la parrilla y pepino',
                author: 'Dolly Irigoyen',
                descripcion: 'Una deliciosa comida con semillas de sésamo tostadas. Vegano, sin gluten. Para 4 personas, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 60,
                precio: 135,
                estrellas: 3.3,
                video: video1,
                categoria: 'Veggie',
              },
              {
                id: 36,
                img: image36,
                title: 'Gnocchi alla Trapanese',
                author: 'Donato Di Santis',
                descripcion: '¡Imperdibles ñoquis! Las almendras cremosas toman el centro del escenario. Además de dar textura a toda la pasta, también te proporcionan proteínas y grasas insaturadas. Para 2 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 25,
                precio: 140,
                estrellas: 3.6,
                video: video1,
                categoria: 'Veggie',
              },
              {
                id: 37,
                img: image37,
                title: 'Cranachan de arándano congelado',
                author: 'Osvaldo Gross',
                descripcion: 'Un cremoso semifrío inspirado en el postre de avena escocés cranachan, y coronado con una crema Drambuie. Cumple todos los requisitos en cuanto a capas, sabor y textura. Para 12 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 60,
                precio: 160,
                estrellas: 3.8,
                video: video1,
                categoria: 'Tentaciones',
              },
              {
                id: 38,
                img: image38,
                title: 'Torta de chocolate Guinness',
                author: 'Maru Botana',
                descripcion: 'Con una mezcla embriagadora de Guinness y chocolate, esta torta es una delicia. Rico y oscuro, la amargura aterciopelada de la Guinness resalta el sabor del chocolate, por lo que tiene un sabor fuerte, mientras le da a la esponja un sabor sutil. La riqueza se equilibra con la dulzura del glaseado de crema agria, que hace que se parezca a la famosa stout irlandesa, negra con una cabeza cremosa. Para 10 porciones, dificultad: "no demasiado complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 70,
                precio: 170,
                estrellas: 4.0,
                video: video1,
                categoria: 'Tentaciones',
              },
              {
                id: 39,
                img: image39,
                title: 'Mousse de chocolate con ciruelas',
                author: 'Buddy Valastro',
                descripcion: 'Riquísimo y tentador postre vegetariano y sin gluten. Cualquier mezcla de ciruela pasa se mantendrá en un recipiente hermético hasta un mes. Rinde para 12/14 porciones, dificultad: "no tan complicado".',
                ingredientes: '350 g de chocolate negro (70%), más extra para servir.100 ml de crema doble.10 huevos.50 g de azúcar en polvo de oro.500 g de ciruelas secas.150 ml de whisky.100 ml de jugo de naranja sin azúcar fresco',
                receta: 'Prepara las ciruelas la noche anterior: combina las ciruelas pasas, el whisky y el jugo de naranja en un tazón y déjalo en remojo toda la noche. Al día siguiente, divida el chocolate y derrita en un recipiente colocado sobre una fuente de agua hirviendo, asegurándose de que el recipiente no toque el agua. Retire el recipiente del fuego y déjelo enfriar.',
                tiempo: 150,
                precio: 165,
                estrellas: 3.7,
                video: video1,
                categoria: 'Tentaciones',
              },
              {
                id: 40,
                img: image40,
                title: 'Blackcurrant ombré cheesecake',
                author: 'Buddy Valastro',
                descripcion: 'Este cheesecake con base de galleta de avena y cobertura de gelatina de bayas sabe tan bien como parece. El efecto ombré es una gran pieza central: ¡tus amigos nunca adivinarán lo fácil que es hacer! Para 12 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 45,
                precio: 120,
                estrellas: 3.5,
                video: video1,
                categoria: 'Tentaciones',
              },
              {
                id: 41,
                img: image41,
                title: 'Helado de banana y canela',
                author: 'Utilísima',
                descripcion: 'Increíble helado vegetariano y sin gluten. Postre fácil de hacer y tan difícil de resistir. Para 8 porciones, dificultad: "súper fácil".',
                ingredientes: '',
                receta: '',
                tiempo: 30,
                precio: 100,
                estrellas: 3.2,
                video: video1,
                categoria: 'Tentaciones',
              },
              {
                id: 42,
                img: image42,
                title: 'Torta de chocolate',
                author: 'Jamie Oliver',
                descripcion: 'Torta sin gluten súper rápida de hacer. El polen de abeja proporciona el intenso estallido de sabores a miel y su crujido satisfactorio. Para 16 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 25,
                precio: 130,
                estrellas: 3.7,
                video: video1,
                categoria: 'Tentaciones',
              },
              {
                id: 43,
                img: image43,
                title: 'Torta de calabaza con nueces pecanas',
                author: 'Jamie Oliver',
                descripcion: 'Con un topping crujiente de nueces pegajoso y dulce, ¡es un verdadero placer! Proporciona una dulzura natural. Para 12 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 170,
                precio: 160,
                estrellas: 3.5,
                video: video1,
                categoria: 'Tentaciones',
              },
              {
                id: 44,
                img: image44,
                title: 'Squaffee pie',
                author: 'Utilísima',
                descripcion: 'Fabuloso postre vegetariano con una llovizna de caramelo de café. Posee un relleno denso y rico, perfecto para capas con caramelo. Para 12 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 90,
                precio: 145,
                estrellas: 3.4,
                video: video1,
                categoria: 'Tentaciones',
              },
              {
                id: 45,
                img: image45,
                title: 'Tarta de manzana',
                author: 'Maru Botana',
                descripcion: 'Esta versión es ligeramente especiada y absolutamente deliciosa ahogada en natillas. Para 6 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 90,
                precio: 120,
                estrellas: 3.2,
                video: video1,
                categoria: 'Tentaciones',
              },
              {
                id: 46,
                img: image46,
                title: 'Hot cross muffins',
                author: 'Utilísima',
                descripcion: 'Un regalo de Pascuas sin gluten. Para 24 porciones, dificultad: "no tan complicado".',
                ingredientes: '',
                receta: '',
                tiempo: 80,
                precio: 110,
                estrellas: 3.3,
                video: video1,
                categoria: 'Tentaciones',
              },
              {
                id: 47,
                img: image47,
                title: 'Deliciosa mousse de chocolate',
                author: 'Buddy Valastro',
                descripcion: 'Riquisimo postre sin gluten, con guindas y chapas de sésamo molidas. Esta receta de mousse de chocolate está repleta de ingredientes deliciosos y un poco traviesos. Para 10 porciones, dificultad: "súper fácil".',
                ingredientes: '',
                receta: '',
                tiempo: 30,
                precio: 135,
                estrellas: 4.4,
                video: video1,
                categoria: 'Tentaciones',
              },
              {
                id: 48,
                img: image48,
                title: 'Tarta de rizo de limón',
                author: 'Utilísima',
                descripcion: 'Deliciosa tarta vegetariana. Con sólo un bocado obtendrá un suave relleno de limón, una masa quebradiza y un poco de azúcar caramelizado. Para 10 porciones, dificultad: "para presumir".',
                ingredientes: '',
                receta: '',
                tiempo: 60,
                precio: 120,
                estrellas: 3.5,
                video: video1,
                categoria: 'Tentaciones',
              }
            ],
  };

export default appData;